// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ActionInfo.proto

#ifndef PROTOBUF_ActionInfo_2eproto__INCLUDED
#define PROTOBUF_ActionInfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace SAC {
class ActionInfo;
class ActionInfoDefaultTypeInternal;
extern ActionInfoDefaultTypeInternal _ActionInfo_default_instance_;
}  // namespace SAC

namespace SAC {

namespace protobuf_ActionInfo_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_ActionInfo_2eproto

// ===================================================================

class ActionInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SAC.ActionInfo) */ {
 public:
  ActionInfo();
  virtual ~ActionInfo();

  ActionInfo(const ActionInfo& from);

  inline ActionInfo& operator=(const ActionInfo& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ActionInfo& default_instance();

  static inline const ActionInfo* internal_default_instance() {
    return reinterpret_cast<const ActionInfo*>(
               &_ActionInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ActionInfo* other);

  // implements Message ----------------------------------------------

  inline ActionInfo* New() const PROTOBUF_FINAL { return New(NULL); }

  ActionInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ActionInfo& from);
  void MergeFrom(const ActionInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ActionInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string ChargingRuleName = 2;
  void clear_chargingrulename();
  static const int kChargingRuleNameFieldNumber = 2;
  const ::std::string& chargingrulename() const;
  void set_chargingrulename(const ::std::string& value);
  #if LANG_CXX11
  void set_chargingrulename(::std::string&& value);
  #endif
  void set_chargingrulename(const char* value);
  void set_chargingrulename(const char* value, size_t size);
  ::std::string* mutable_chargingrulename();
  ::std::string* release_chargingrulename();
  void set_allocated_chargingrulename(::std::string* chargingrulename);

  // int32 ActionID = 1;
  void clear_actionid();
  static const int kActionIDFieldNumber = 1;
  ::google::protobuf::int32 actionid() const;
  void set_actionid(::google::protobuf::int32 value);

  // int32 Result = 3;
  void clear_result();
  static const int kResultFieldNumber = 3;
  ::google::protobuf::int32 result() const;
  void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:SAC.ActionInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr chargingrulename_;
  ::google::protobuf::int32 actionid_;
  ::google::protobuf::int32 result_;
  mutable int _cached_size_;
  friend struct protobuf_ActionInfo_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ActionInfo

// int32 ActionID = 1;
inline void ActionInfo::clear_actionid() {
  actionid_ = 0;
}
inline ::google::protobuf::int32 ActionInfo::actionid() const {
  // @@protoc_insertion_point(field_get:SAC.ActionInfo.ActionID)
  return actionid_;
}
inline void ActionInfo::set_actionid(::google::protobuf::int32 value) {
  
  actionid_ = value;
  // @@protoc_insertion_point(field_set:SAC.ActionInfo.ActionID)
}

// string ChargingRuleName = 2;
inline void ActionInfo::clear_chargingrulename() {
  chargingrulename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ActionInfo::chargingrulename() const {
  // @@protoc_insertion_point(field_get:SAC.ActionInfo.ChargingRuleName)
  return chargingrulename_.GetNoArena();
}
inline void ActionInfo::set_chargingrulename(const ::std::string& value) {
  
  chargingrulename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SAC.ActionInfo.ChargingRuleName)
}
#if LANG_CXX11
inline void ActionInfo::set_chargingrulename(::std::string&& value) {
  
  chargingrulename_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:SAC.ActionInfo.ChargingRuleName)
}
#endif
inline void ActionInfo::set_chargingrulename(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  chargingrulename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SAC.ActionInfo.ChargingRuleName)
}
inline void ActionInfo::set_chargingrulename(const char* value, size_t size) {
  
  chargingrulename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SAC.ActionInfo.ChargingRuleName)
}
inline ::std::string* ActionInfo::mutable_chargingrulename() {
  
  // @@protoc_insertion_point(field_mutable:SAC.ActionInfo.ChargingRuleName)
  return chargingrulename_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ActionInfo::release_chargingrulename() {
  // @@protoc_insertion_point(field_release:SAC.ActionInfo.ChargingRuleName)
  
  return chargingrulename_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ActionInfo::set_allocated_chargingrulename(::std::string* chargingrulename) {
  if (chargingrulename != NULL) {
    
  } else {
    
  }
  chargingrulename_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), chargingrulename);
  // @@protoc_insertion_point(field_set_allocated:SAC.ActionInfo.ChargingRuleName)
}

// int32 Result = 3;
inline void ActionInfo::clear_result() {
  result_ = 0;
}
inline ::google::protobuf::int32 ActionInfo::result() const {
  // @@protoc_insertion_point(field_get:SAC.ActionInfo.Result)
  return result_;
}
inline void ActionInfo::set_result(::google::protobuf::int32 value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:SAC.ActionInfo.Result)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace SAC

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ActionInfo_2eproto__INCLUDED
