// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CurrentDate.proto

#ifndef PROTOBUF_CurrentDate_2eproto__INCLUDED
#define PROTOBUF_CurrentDate_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace SAC {
class CurrentDate;
class CurrentDateDefaultTypeInternal;
extern CurrentDateDefaultTypeInternal _CurrentDate_default_instance_;
}  // namespace SAC

namespace SAC {

namespace protobuf_CurrentDate_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_CurrentDate_2eproto

// ===================================================================

class CurrentDate : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SAC.CurrentDate) */ {
 public:
  CurrentDate();
  virtual ~CurrentDate();

  CurrentDate(const CurrentDate& from);

  inline CurrentDate& operator=(const CurrentDate& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CurrentDate& default_instance();

  static inline const CurrentDate* internal_default_instance() {
    return reinterpret_cast<const CurrentDate*>(
               &_CurrentDate_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(CurrentDate* other);

  // implements Message ----------------------------------------------

  inline CurrentDate* New() const PROTOBUF_FINAL { return New(NULL); }

  CurrentDate* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CurrentDate& from);
  void MergeFrom(const CurrentDate& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CurrentDate* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 Year = 1;
  void clear_year();
  static const int kYearFieldNumber = 1;
  ::google::protobuf::int32 year() const;
  void set_year(::google::protobuf::int32 value);

  // int32 Month = 2;
  void clear_month();
  static const int kMonthFieldNumber = 2;
  ::google::protobuf::int32 month() const;
  void set_month(::google::protobuf::int32 value);

  // int32 Day = 3;
  void clear_day();
  static const int kDayFieldNumber = 3;
  ::google::protobuf::int32 day() const;
  void set_day(::google::protobuf::int32 value);

  // int32 Hour = 4;
  void clear_hour();
  static const int kHourFieldNumber = 4;
  ::google::protobuf::int32 hour() const;
  void set_hour(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:SAC.CurrentDate)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 year_;
  ::google::protobuf::int32 month_;
  ::google::protobuf::int32 day_;
  ::google::protobuf::int32 hour_;
  mutable int _cached_size_;
  friend struct protobuf_CurrentDate_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CurrentDate

// int32 Year = 1;
inline void CurrentDate::clear_year() {
  year_ = 0;
}
inline ::google::protobuf::int32 CurrentDate::year() const {
  // @@protoc_insertion_point(field_get:SAC.CurrentDate.Year)
  return year_;
}
inline void CurrentDate::set_year(::google::protobuf::int32 value) {
  
  year_ = value;
  // @@protoc_insertion_point(field_set:SAC.CurrentDate.Year)
}

// int32 Month = 2;
inline void CurrentDate::clear_month() {
  month_ = 0;
}
inline ::google::protobuf::int32 CurrentDate::month() const {
  // @@protoc_insertion_point(field_get:SAC.CurrentDate.Month)
  return month_;
}
inline void CurrentDate::set_month(::google::protobuf::int32 value) {
  
  month_ = value;
  // @@protoc_insertion_point(field_set:SAC.CurrentDate.Month)
}

// int32 Day = 3;
inline void CurrentDate::clear_day() {
  day_ = 0;
}
inline ::google::protobuf::int32 CurrentDate::day() const {
  // @@protoc_insertion_point(field_get:SAC.CurrentDate.Day)
  return day_;
}
inline void CurrentDate::set_day(::google::protobuf::int32 value) {
  
  day_ = value;
  // @@protoc_insertion_point(field_set:SAC.CurrentDate.Day)
}

// int32 Hour = 4;
inline void CurrentDate::clear_hour() {
  hour_ = 0;
}
inline ::google::protobuf::int32 CurrentDate::hour() const {
  // @@protoc_insertion_point(field_get:SAC.CurrentDate.Hour)
  return hour_;
}
inline void CurrentDate::set_hour(::google::protobuf::int32 value) {
  
  hour_ = value;
  // @@protoc_insertion_point(field_set:SAC.CurrentDate.Hour)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace SAC

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CurrentDate_2eproto__INCLUDED
