// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubscrInfo.proto

#ifndef PROTOBUF_SubscrInfo_2eproto__INCLUDED
#define PROTOBUF_SubscrInfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace SAC {
class SubscrInfo;
class SubscrInfoDefaultTypeInternal;
extern SubscrInfoDefaultTypeInternal _SubscrInfo_default_instance_;
}  // namespace SAC

namespace SAC {

namespace protobuf_SubscrInfo_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_SubscrInfo_2eproto

// ===================================================================

class SubscrInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SAC.SubscrInfo) */ {
 public:
  SubscrInfo();
  virtual ~SubscrInfo();

  SubscrInfo(const SubscrInfo& from);

  inline SubscrInfo& operator=(const SubscrInfo& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SubscrInfo& default_instance();

  static inline const SubscrInfo* internal_default_instance() {
    return reinterpret_cast<const SubscrInfo*>(
               &_SubscrInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(SubscrInfo* other);

  // implements Message ----------------------------------------------

  inline SubscrInfo* New() const PROTOBUF_FINAL { return New(NULL); }

  SubscrInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SubscrInfo& from);
  void MergeFrom(const SubscrInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SubscrInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 PlanID = 1;
  void clear_planid();
  static const int kPlanIDFieldNumber = 1;
  ::google::protobuf::int32 planid() const;
  void set_planid(::google::protobuf::int32 value);

  // int32 Activate = 2;
  void clear_activate();
  static const int kActivateFieldNumber = 2;
  ::google::protobuf::int32 activate() const;
  void set_activate(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:SAC.SubscrInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 planid_;
  ::google::protobuf::int32 activate_;
  mutable int _cached_size_;
  friend struct protobuf_SubscrInfo_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// SubscrInfo

// int32 PlanID = 1;
inline void SubscrInfo::clear_planid() {
  planid_ = 0;
}
inline ::google::protobuf::int32 SubscrInfo::planid() const {
  // @@protoc_insertion_point(field_get:SAC.SubscrInfo.PlanID)
  return planid_;
}
inline void SubscrInfo::set_planid(::google::protobuf::int32 value) {
  
  planid_ = value;
  // @@protoc_insertion_point(field_set:SAC.SubscrInfo.PlanID)
}

// int32 Activate = 2;
inline void SubscrInfo::clear_activate() {
  activate_ = 0;
}
inline ::google::protobuf::int32 SubscrInfo::activate() const {
  // @@protoc_insertion_point(field_get:SAC.SubscrInfo.Activate)
  return activate_;
}
inline void SubscrInfo::set_activate(::google::protobuf::int32 value) {
  
  activate_ = value;
  // @@protoc_insertion_point(field_set:SAC.SubscrInfo.Activate)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace SAC

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_SubscrInfo_2eproto__INCLUDED
