/*
 * Nudm_UECM API
 * This is a UDM Server API.   [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 0.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.api;

import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.ApiCallback;
import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.ApiClient;
import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.ApiException;
import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.ApiResponse;
import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.Configuration;
import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.Pair;
import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.ProgressRequestBody;
import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.model.Amf3GppAccessRegistration;
import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.model.Amf3GppAccessRegistrationModification;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Amf3gppAccessApi {
    private ApiClient apiClient;

    public Amf3gppAccessApi() {
        this(Configuration.getDefaultApiClient());
    }

    public Amf3gppAccessApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for getAmf3gppAccess
     * @param ueId ueId.  (required)
     * @param supportedFeatures  (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getAmf3gppAccessCall(String ueId, String supportedFeatures, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/{ueId}/registrations/amf-3gpp-access"
            .replaceAll("\\{" + "ueId" + "\\}", apiClient.escapeString(ueId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (supportedFeatures != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("supportedFeatures", supportedFeatures));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json", "application/xml"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json", "application/xml"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getAmf3gppAccessValidateBeforeCall(String ueId, String supportedFeatures, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'ueId' is set
        if (ueId == null) {
            throw new ApiException("Missing the required parameter 'ueId' when calling getAmf3gppAccess(Async)");
        }
        

        com.squareup.okhttp.Call call = getAmf3gppAccessCall(ueId, supportedFeatures, progressListener, progressRequestListener);
        return call;

    }

    /**
     * amf-3gpp-access.
     * see 29.503 6.2.3.2
     * @param ueId ueId.  (required)
     * @param supportedFeatures  (optional)
     * @return Amf3GppAccessRegistration
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Amf3GppAccessRegistration getAmf3gppAccess(String ueId, String supportedFeatures) throws ApiException {
        ApiResponse<Amf3GppAccessRegistration> resp = getAmf3gppAccessWithHttpInfo(ueId, supportedFeatures);
        return resp.getData();
    }

    /**
     * amf-3gpp-access.
     * see 29.503 6.2.3.2
     * @param ueId ueId.  (required)
     * @param supportedFeatures  (optional)
     * @return ApiResponse&lt;Amf3GppAccessRegistration&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Amf3GppAccessRegistration> getAmf3gppAccessWithHttpInfo(String ueId, String supportedFeatures) throws ApiException {
        com.squareup.okhttp.Call call = getAmf3gppAccessValidateBeforeCall(ueId, supportedFeatures, null, null);
        Type localVarReturnType = new TypeToken<Amf3GppAccessRegistration>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * amf-3gpp-access. (asynchronously)
     * see 29.503 6.2.3.2
     * @param ueId ueId.  (required)
     * @param supportedFeatures  (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getAmf3gppAccessAsync(String ueId, String supportedFeatures, final ApiCallback<Amf3GppAccessRegistration> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getAmf3gppAccessValidateBeforeCall(ueId, supportedFeatures, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Amf3GppAccessRegistration>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for patchAmf3gppAccess
     * @param ueId ueId.  (required)
     * @param amf3GppAccessRegistrationModification The AMF registration for 3GPP access is replaced with the received information (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call patchAmf3gppAccessCall(String ueId, Amf3GppAccessRegistrationModification amf3GppAccessRegistrationModification, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = amf3GppAccessRegistrationModification;

        // create path and map variables
        String localVarPath = "/{ueId}/registrations/amf-3gpp-access"
            .replaceAll("\\{" + "ueId" + "\\}", apiClient.escapeString(ueId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json", "application/xml"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json", "application/xml"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call patchAmf3gppAccessValidateBeforeCall(String ueId, Amf3GppAccessRegistrationModification amf3GppAccessRegistrationModification, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'ueId' is set
        if (ueId == null) {
            throw new ApiException("Missing the required parameter 'ueId' when calling patchAmf3gppAccess(Async)");
        }
        
        // verify the required parameter 'amf3GppAccessRegistrationModification' is set
        if (amf3GppAccessRegistrationModification == null) {
            throw new ApiException("Missing the required parameter 'amf3GppAccessRegistrationModification' when calling patchAmf3gppAccess(Async)");
        }
        

        com.squareup.okhttp.Call call = patchAmf3gppAccessCall(ueId, amf3GppAccessRegistrationModification, progressListener, progressRequestListener);
        return call;

    }

    /**
     * amf-3gpp-access.
     * see 29.503 6.2.3.2
     * @param ueId ueId.  (required)
     * @param amf3GppAccessRegistrationModification The AMF registration for 3GPP access is replaced with the received information (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void patchAmf3gppAccess(String ueId, Amf3GppAccessRegistrationModification amf3GppAccessRegistrationModification) throws ApiException {
        patchAmf3gppAccessWithHttpInfo(ueId, amf3GppAccessRegistrationModification);
    }

    /**
     * amf-3gpp-access.
     * see 29.503 6.2.3.2
     * @param ueId ueId.  (required)
     * @param amf3GppAccessRegistrationModification The AMF registration for 3GPP access is replaced with the received information (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> patchAmf3gppAccessWithHttpInfo(String ueId, Amf3GppAccessRegistrationModification amf3GppAccessRegistrationModification) throws ApiException {
        com.squareup.okhttp.Call call = patchAmf3gppAccessValidateBeforeCall(ueId, amf3GppAccessRegistrationModification, null, null);
        return apiClient.execute(call);
    }

    /**
     * amf-3gpp-access. (asynchronously)
     * see 29.503 6.2.3.2
     * @param ueId ueId.  (required)
     * @param amf3GppAccessRegistrationModification The AMF registration for 3GPP access is replaced with the received information (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call patchAmf3gppAccessAsync(String ueId, Amf3GppAccessRegistrationModification amf3GppAccessRegistrationModification, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = patchAmf3gppAccessValidateBeforeCall(ueId, amf3GppAccessRegistrationModification, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
    /**
     * Build call for putAmf3gppAccess
     * @param ueId ueId.  (required)
     * @param amf3gppAccessRegistration The AMF registration for 3GPP access is replaced with the received information (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call putAmf3gppAccessCall(String ueId, Amf3GppAccessRegistration amf3gppAccessRegistration, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = amf3gppAccessRegistration;

        // create path and map variables
        String localVarPath = "/{ueId}/registrations/amf-3gpp-access"
            .replaceAll("\\{" + "ueId" + "\\}", apiClient.escapeString(ueId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json", "application/xml"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json", "application/xml"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call putAmf3gppAccessValidateBeforeCall(String ueId, Amf3GppAccessRegistration amf3gppAccessRegistration, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'ueId' is set
        if (ueId == null) {
            throw new ApiException("Missing the required parameter 'ueId' when calling putAmf3gppAccess(Async)");
        }
        
        // verify the required parameter 'amf3gppAccessRegistration' is set
        if (amf3gppAccessRegistration == null) {
            throw new ApiException("Missing the required parameter 'amf3gppAccessRegistration' when calling putAmf3gppAccess(Async)");
        }
        

        com.squareup.okhttp.Call call = putAmf3gppAccessCall(ueId, amf3gppAccessRegistration, progressListener, progressRequestListener);
        return call;

    }

    /**
     * amf-3gpp-access.
     * see 29.503 6.2.3.2
     * @param ueId ueId.  (required)
     * @param amf3gppAccessRegistration The AMF registration for 3GPP access is replaced with the received information (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void putAmf3gppAccess(String ueId, Amf3GppAccessRegistration amf3gppAccessRegistration) throws ApiException {
        putAmf3gppAccessWithHttpInfo(ueId, amf3gppAccessRegistration);
    }

    /**
     * amf-3gpp-access.
     * see 29.503 6.2.3.2
     * @param ueId ueId.  (required)
     * @param amf3gppAccessRegistration The AMF registration for 3GPP access is replaced with the received information (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> putAmf3gppAccessWithHttpInfo(String ueId, Amf3GppAccessRegistration amf3gppAccessRegistration) throws ApiException {
        com.squareup.okhttp.Call call = putAmf3gppAccessValidateBeforeCall(ueId, amf3gppAccessRegistration, null, null);
        return apiClient.execute(call);
    }

    /**
     * amf-3gpp-access. (asynchronously)
     * see 29.503 6.2.3.2
     * @param ueId ueId.  (required)
     * @param amf3gppAccessRegistration The AMF registration for 3GPP access is replaced with the received information (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call putAmf3gppAccessAsync(String ueId, Amf3GppAccessRegistration amf3gppAccessRegistration, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = putAmf3gppAccessValidateBeforeCall(ueId, amf3gppAccessRegistration, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
}
