/*
 * Nudm_UECM API
 * This is a UDM Server API.   [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 0.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.api;

import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.ApiCallback;
import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.ApiClient;
import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.ApiException;
import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.ApiResponse;
import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.Configuration;
import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.Pair;
import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.ProgressRequestBody;
import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.model.SmfRegistration;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class IndividualSmfRegistrationApi {
    private ApiClient apiClient;

    public IndividualSmfRegistrationApi() {
        this(Configuration.getDefaultApiClient());
    }

    public IndividualSmfRegistrationApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for deleteIndividualSmfRegistration
     * @param ueId ueId.  (required)
     * @param pduSessionId pduSessionId.  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call deleteIndividualSmfRegistrationCall(String ueId, String pduSessionId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/{ueId}/registrations/smf-registrations/{pduSessionId}"
            .replaceAll("\\{" + "ueId" + "\\}", apiClient.escapeString(ueId.toString()))
            .replaceAll("\\{" + "pduSessionId" + "\\}", apiClient.escapeString(pduSessionId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json", "application/xml"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json", "application/xml"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call deleteIndividualSmfRegistrationValidateBeforeCall(String ueId, String pduSessionId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'ueId' is set
        if (ueId == null) {
            throw new ApiException("Missing the required parameter 'ueId' when calling deleteIndividualSmfRegistration(Async)");
        }
        
        // verify the required parameter 'pduSessionId' is set
        if (pduSessionId == null) {
            throw new ApiException("Missing the required parameter 'pduSessionId' when calling deleteIndividualSmfRegistration(Async)");
        }
        

        com.squareup.okhttp.Call call = deleteIndividualSmfRegistrationCall(ueId, pduSessionId, progressListener, progressRequestListener);
        return call;

    }

    /**
     * individual-smf-registration.
     * see 29.503 6.2.3.5
     * @param ueId ueId.  (required)
     * @param pduSessionId pduSessionId.  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void deleteIndividualSmfRegistration(String ueId, String pduSessionId) throws ApiException {
        deleteIndividualSmfRegistrationWithHttpInfo(ueId, pduSessionId);
    }

    /**
     * individual-smf-registration.
     * see 29.503 6.2.3.5
     * @param ueId ueId.  (required)
     * @param pduSessionId pduSessionId.  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> deleteIndividualSmfRegistrationWithHttpInfo(String ueId, String pduSessionId) throws ApiException {
        com.squareup.okhttp.Call call = deleteIndividualSmfRegistrationValidateBeforeCall(ueId, pduSessionId, null, null);
        return apiClient.execute(call);
    }

    /**
     * individual-smf-registration. (asynchronously)
     * see 29.503 6.2.3.5
     * @param ueId ueId.  (required)
     * @param pduSessionId pduSessionId.  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call deleteIndividualSmfRegistrationAsync(String ueId, String pduSessionId, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = deleteIndividualSmfRegistrationValidateBeforeCall(ueId, pduSessionId, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
    /**
     * Build call for putIndividualSmfRegistration
     * @param ueId ueId.  (required)
     * @param pduSessionId pduSessionId.  (required)
     * @param smfRegistration The registration that is to be created. (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call putIndividualSmfRegistrationCall(String ueId, String pduSessionId, SmfRegistration smfRegistration, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = smfRegistration;

        // create path and map variables
        String localVarPath = "/{ueId}/registrations/smf-registrations/{pduSessionId}"
            .replaceAll("\\{" + "ueId" + "\\}", apiClient.escapeString(ueId.toString()))
            .replaceAll("\\{" + "pduSessionId" + "\\}", apiClient.escapeString(pduSessionId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json", "application/xml"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json", "application/xml"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call putIndividualSmfRegistrationValidateBeforeCall(String ueId, String pduSessionId, SmfRegistration smfRegistration, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'ueId' is set
        if (ueId == null) {
            throw new ApiException("Missing the required parameter 'ueId' when calling putIndividualSmfRegistration(Async)");
        }
        
        // verify the required parameter 'pduSessionId' is set
        if (pduSessionId == null) {
            throw new ApiException("Missing the required parameter 'pduSessionId' when calling putIndividualSmfRegistration(Async)");
        }
        
        // verify the required parameter 'smfRegistration' is set
        if (smfRegistration == null) {
            throw new ApiException("Missing the required parameter 'smfRegistration' when calling putIndividualSmfRegistration(Async)");
        }
        

        com.squareup.okhttp.Call call = putIndividualSmfRegistrationCall(ueId, pduSessionId, smfRegistration, progressListener, progressRequestListener);
        return call;

    }

    /**
     * individual-smf-registration.
     * see 29.503 6.2.3.5
     * @param ueId ueId.  (required)
     * @param pduSessionId pduSessionId.  (required)
     * @param smfRegistration The registration that is to be created. (required)
     * @return SmfRegistration
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public SmfRegistration putIndividualSmfRegistration(String ueId, String pduSessionId, SmfRegistration smfRegistration) throws ApiException {
        ApiResponse<SmfRegistration> resp = putIndividualSmfRegistrationWithHttpInfo(ueId, pduSessionId, smfRegistration);
        return resp.getData();
    }

    /**
     * individual-smf-registration.
     * see 29.503 6.2.3.5
     * @param ueId ueId.  (required)
     * @param pduSessionId pduSessionId.  (required)
     * @param smfRegistration The registration that is to be created. (required)
     * @return ApiResponse&lt;SmfRegistration&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<SmfRegistration> putIndividualSmfRegistrationWithHttpInfo(String ueId, String pduSessionId, SmfRegistration smfRegistration) throws ApiException {
        com.squareup.okhttp.Call call = putIndividualSmfRegistrationValidateBeforeCall(ueId, pduSessionId, smfRegistration, null, null);
        Type localVarReturnType = new TypeToken<SmfRegistration>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * individual-smf-registration. (asynchronously)
     * see 29.503 6.2.3.5
     * @param ueId ueId.  (required)
     * @param pduSessionId pduSessionId.  (required)
     * @param smfRegistration The registration that is to be created. (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call putIndividualSmfRegistrationAsync(String ueId, String pduSessionId, SmfRegistration smfRegistration, final ApiCallback<SmfRegistration> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = putIndividualSmfRegistrationValidateBeforeCall(ueId, pduSessionId, smfRegistration, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<SmfRegistration>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
