/*
 * Nudm_UECM API
 * This is a UDM Server API.   [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 0.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.api;

import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.ApiCallback;
import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.ApiClient;
import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.ApiException;
import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.ApiResponse;
import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.Configuration;
import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.Pair;
import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.ProgressRequestBody;
import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.model.SmsfRegistration;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Smsf3gppAccessApi {
    private ApiClient apiClient;

    public Smsf3gppAccessApi() {
        this(Configuration.getDefaultApiClient());
    }

    public Smsf3gppAccessApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for deleteSmsf3gppAccess
     * @param ueId ueId.  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call deleteSmsf3gppAccessCall(String ueId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/{ueId}/registrations/smsf-3gpp-access"
            .replaceAll("\\{" + "ueId" + "\\}", apiClient.escapeString(ueId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json", "application/xml"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json", "application/xml"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call deleteSmsf3gppAccessValidateBeforeCall(String ueId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'ueId' is set
        if (ueId == null) {
            throw new ApiException("Missing the required parameter 'ueId' when calling deleteSmsf3gppAccess(Async)");
        }
        

        com.squareup.okhttp.Call call = deleteSmsf3gppAccessCall(ueId, progressListener, progressRequestListener);
        return call;

    }

    /**
     * smsf-3gpp-access.
     * see 29.503 6.2.3.6
     * @param ueId ueId.  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void deleteSmsf3gppAccess(String ueId) throws ApiException {
        deleteSmsf3gppAccessWithHttpInfo(ueId);
    }

    /**
     * smsf-3gpp-access.
     * see 29.503 6.2.3.6
     * @param ueId ueId.  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> deleteSmsf3gppAccessWithHttpInfo(String ueId) throws ApiException {
        com.squareup.okhttp.Call call = deleteSmsf3gppAccessValidateBeforeCall(ueId, null, null);
        return apiClient.execute(call);
    }

    /**
     * smsf-3gpp-access. (asynchronously)
     * see 29.503 6.2.3.6
     * @param ueId ueId.  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call deleteSmsf3gppAccessAsync(String ueId, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = deleteSmsf3gppAccessValidateBeforeCall(ueId, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
    /**
     * Build call for getSmsf3gppAccess
     * @param ueId ueId.  (required)
     * @param supportedFeatures  (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getSmsf3gppAccessCall(String ueId, String supportedFeatures, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/{ueId}/registrations/smsf-3gpp-access"
            .replaceAll("\\{" + "ueId" + "\\}", apiClient.escapeString(ueId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (supportedFeatures != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("supportedFeatures", supportedFeatures));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json", "application/xml"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json", "application/xml"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getSmsf3gppAccessValidateBeforeCall(String ueId, String supportedFeatures, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'ueId' is set
        if (ueId == null) {
            throw new ApiException("Missing the required parameter 'ueId' when calling getSmsf3gppAccess(Async)");
        }
        

        com.squareup.okhttp.Call call = getSmsf3gppAccessCall(ueId, supportedFeatures, progressListener, progressRequestListener);
        return call;

    }

    /**
     * smsf-3gpp-access.
     * see 29.503 6.2.3.7
     * @param ueId ueId.  (required)
     * @param supportedFeatures  (optional)
     * @return SmsfRegistration
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public SmsfRegistration getSmsf3gppAccess(String ueId, String supportedFeatures) throws ApiException {
        ApiResponse<SmsfRegistration> resp = getSmsf3gppAccessWithHttpInfo(ueId, supportedFeatures);
        return resp.getData();
    }

    /**
     * smsf-3gpp-access.
     * see 29.503 6.2.3.7
     * @param ueId ueId.  (required)
     * @param supportedFeatures  (optional)
     * @return ApiResponse&lt;SmsfRegistration&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<SmsfRegistration> getSmsf3gppAccessWithHttpInfo(String ueId, String supportedFeatures) throws ApiException {
        com.squareup.okhttp.Call call = getSmsf3gppAccessValidateBeforeCall(ueId, supportedFeatures, null, null);
        Type localVarReturnType = new TypeToken<SmsfRegistration>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * smsf-3gpp-access. (asynchronously)
     * see 29.503 6.2.3.7
     * @param ueId ueId.  (required)
     * @param supportedFeatures  (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getSmsf3gppAccessAsync(String ueId, String supportedFeatures, final ApiCallback<SmsfRegistration> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getSmsf3gppAccessValidateBeforeCall(ueId, supportedFeatures, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<SmsfRegistration>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for putSmsf3gppAccess
     * @param ueId ueId.  (required)
     * @param smsfRegistration The SMSF registration for 3GPP access is created or updated with the received information. (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call putSmsf3gppAccessCall(String ueId, SmsfRegistration smsfRegistration, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = smsfRegistration;

        // create path and map variables
        String localVarPath = "/{ueId}/registrations/smsf-3gpp-access"
            .replaceAll("\\{" + "ueId" + "\\}", apiClient.escapeString(ueId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json", "application/xml"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json", "application/xml"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call putSmsf3gppAccessValidateBeforeCall(String ueId, SmsfRegistration smsfRegistration, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'ueId' is set
        if (ueId == null) {
            throw new ApiException("Missing the required parameter 'ueId' when calling putSmsf3gppAccess(Async)");
        }
        
        // verify the required parameter 'smsfRegistration' is set
        if (smsfRegistration == null) {
            throw new ApiException("Missing the required parameter 'smsfRegistration' when calling putSmsf3gppAccess(Async)");
        }
        

        com.squareup.okhttp.Call call = putSmsf3gppAccessCall(ueId, smsfRegistration, progressListener, progressRequestListener);
        return call;

    }

    /**
     * smsf-3gpp-access.
     * see 29.503 6.2.3.5
     * @param ueId ueId.  (required)
     * @param smsfRegistration The SMSF registration for 3GPP access is created or updated with the received information. (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void putSmsf3gppAccess(String ueId, SmsfRegistration smsfRegistration) throws ApiException {
        putSmsf3gppAccessWithHttpInfo(ueId, smsfRegistration);
    }

    /**
     * smsf-3gpp-access.
     * see 29.503 6.2.3.5
     * @param ueId ueId.  (required)
     * @param smsfRegistration The SMSF registration for 3GPP access is created or updated with the received information. (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> putSmsf3gppAccessWithHttpInfo(String ueId, SmsfRegistration smsfRegistration) throws ApiException {
        com.squareup.okhttp.Call call = putSmsf3gppAccessValidateBeforeCall(ueId, smsfRegistration, null, null);
        return apiClient.execute(call);
    }

    /**
     * smsf-3gpp-access. (asynchronously)
     * see 29.503 6.2.3.5
     * @param ueId ueId.  (required)
     * @param smsfRegistration The SMSF registration for 3GPP access is created or updated with the received information. (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call putSmsf3gppAccessAsync(String ueId, SmsfRegistration smsfRegistration, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = putSmsf3gppAccessValidateBeforeCall(ueId, smsfRegistration, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
}
