/*
 * phpipam API(for SMF)
 * phpipam API(for SMF)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nec.corestudy.smf.Repository.phpipam_API_client.api;

import com.nec.corestudy.smf.Repository.phpipam_API_client.ApiException;
import com.nec.corestudy.smf.Repository.phpipam_API_client.model.CreateNewAddressData;
import com.nec.corestudy.smf.Repository.phpipam_API_client.model.DeleteAddressData;
import com.nec.corestudy.smf.Repository.phpipam_API_client.model.SubnetsAddressData;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AddressesApi
 */
@Ignore
public class AddressesApiTest {

    private final AddressesApi api = new AddressesApi();

    
    /**
     * Creates new address in subnets
     *
     * Creates new address in subnets – first available (subnetId can be provided with parameters) 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createsNewAddressInSubnetsTest() throws ApiException {
        Integer subnetId = null;
        CreateNewAddressData body = null;
        SubnetsAddressData response = api.createsNewAddressInSubnets(subnetId, body);

        // TODO: test validations
    }
    
    /**
     * Deletes address
     *
     * Deletes address use &#39;remove_dns&#x3D;1&#39; parameter to remove all related DNS records 1.3  
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deletesAddressTest() throws ApiException {
        Integer id = null;
        DeleteAddressData response = api.deletesAddress(id);

        // TODO: test validations
    }
    
    /**
     * Deletes address
     *
     * Deletes address by IP in specific subnet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deletesAddressByIPInSubnetTest() throws ApiException {
        String ip = null;
        Integer subnetId = null;
        DeleteAddressData response = api.deletesAddressByIPInSubnet(ip, subnetId);

        // TODO: test validations
    }
    
}
