/*
 * Nudm_SDM API
 * This is a UDM Server API.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 0.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.api;

import com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.ApiException;
import com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.model.UeContextInSmfData;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UeContextInSmfDataApi
 */
@Ignore
public class UeContextInSmfDataApiTest {

    private final UeContextInSmfDataApi api = new UeContextInSmfDataApi();

    
    /**
     * UeContextInSmfData
     *
     * see 29.503 6.1.3.7
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUeContextInSmfDataTest() throws ApiException {
        String supi = null;
        String supportedFeatures = null;
        UeContextInSmfData response = api.getUeContextInSmfData(supi, supportedFeatures);

        // TODO: test validations
    }
    
}
