/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.nec.corestudy.udm.NudmSDM.api;

import com.nec.corestudy.udm.NudmSDM.model.IdTranslationResult;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-05-15T19:47:33.905+09:00")

@Api(value = "{gpsi}", description = "the {gpsi} API")
public interface GpsiApi {

    @ApiOperation(value = "IdTranslationResult", nickname = "getIdTranslationResult", notes = "see 29.503 6.1.3.12", response = IdTranslationResult.class, tags={ "IdTranslationResult", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "success", response = IdTranslationResult.class) })
    @RequestMapping(value = "/{gpsi}/id-translation-result",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.GET)
    ResponseEntity<IdTranslationResult> getIdTranslationResult(@ApiParam(value = "",required=true) @PathVariable("gpsi") String gpsi,@ApiParam(value = "[TBD].") @Valid @RequestParam(value = "supportedFeatures", required = false) String supportedFeatures);

}
