/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.nec.corestudy.amf.NamfSmfCLI.api;

import com.nec.corestudy.amf.NamfSmfCLI.model.SmContextCreateData;
import com.nec.corestudy.amf.NamfSmfCLI.model.SmContextCreatedData;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-22T15:38:40.778+09:00")

@Api(value = "SmContextsCollection", description = "the SmContextsCollection API")
public interface SmContextsCollectionApi {

    @ApiOperation(value = "Create SM Context service operation", nickname = "createSMContext", notes = "This resource represents the collection of the individual SM contexts created in the SMF.", response = SmContextCreatedData.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "successful operation", response = SmContextCreatedData.class) })
    @RequestMapping(value = "/sm-contexts",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<SmContextCreatedData> createSMContext(@ApiParam(value = "Representation of the SM context to be created in the SMF" ,required=true )   @RequestBody SmContextCreateData body);

}
