/*
 * Nudm_UECM API
 * This is a UDM Server API.   [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 0.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.api;

import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.ApiException;
import com.nec.corestudy.smf.Controller.Nudm_UECM_API_client.model.SmsfRegistration;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Smsf3gppAccessApi
 */
@Ignore
public class Smsf3gppAccessApiTest {

    private final Smsf3gppAccessApi api = new Smsf3gppAccessApi();

    
    /**
     * smsf-3gpp-access.
     *
     * see 29.503 6.2.3.6
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteSmsf3gppAccessTest() throws ApiException {
        String ueId = null;
        api.deleteSmsf3gppAccess(ueId);

        // TODO: test validations
    }
    
    /**
     * smsf-3gpp-access.
     *
     * see 29.503 6.2.3.7
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSmsf3gppAccessTest() throws ApiException {
        String ueId = null;
        String supportedFeatures = null;
        SmsfRegistration response = api.getSmsf3gppAccess(ueId, supportedFeatures);

        // TODO: test validations
    }
    
    /**
     * smsf-3gpp-access.
     *
     * see 29.503 6.2.3.5
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putSmsf3gppAccessTest() throws ApiException {
        String ueId = null;
        SmsfRegistration smsfRegistration = null;
        api.putSmsf3gppAccess(ueId, smsfRegistration);

        // TODO: test validations
    }
    
}
