/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.nec.corestudy.amf.NamfUecmCLI.api;

import com.nec.corestudy.amf.NamfUecmCLI.model.AmfNon3GppAccessRegistration;
import com.nec.corestudy.amf.NamfUecmCLI.model.AmfNon3GppAccessRegistrationModification;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-15T18:19:23.613+09:00")

@Api(value = "AmfNon3gppAccess", description = "the AmfNon3gppAccess API")
public interface AmfNon3gppAccessApi {

    @ApiOperation(value = "amf-non-3gpp-access.", nickname = "getAmfNon3gppAccess", notes = "see 29.503 6.2.3.3", response = AmfNon3GppAccessRegistration.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK.", response = AmfNon3GppAccessRegistration.class) })
    @RequestMapping(value = "/{ueId}/registrations/amf-non-3gpp-access",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.GET)
    ResponseEntity<AmfNon3GppAccessRegistration> getAmfNon3gppAccess(@ApiParam(value = "ueId. ",required=true) @PathVariable("ueId") String ueId,@ApiParam(value = "")  @RequestParam(value = "supportedFeatures", required = false) String supportedFeatures);


    @ApiOperation(value = "amf-non-3gpp-access.", nickname = "patchAmfNon3gppAccess", notes = "see 29.503 6.2.3.3", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "No Content.") })
    @RequestMapping(value = "/{ueId}/registrations/amf-non-3gpp-access",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.PATCH)
    ResponseEntity<Void> patchAmfNon3gppAccess(@ApiParam(value = "ueId. ",required=true) @PathVariable("ueId") String ueId,@ApiParam(value = "The AMF registration for non 3GPP access is modified with the received information." ,required=true )   @RequestBody AmfNon3GppAccessRegistrationModification amfNon3GppAccessRegistrationModification);


    @ApiOperation(value = "amf-non-3gpp-access.", nickname = "putAmfNon3gppAccess", notes = "see 29.503 6.2.3.3", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "No Content.") })
    @RequestMapping(value = "/{ueId}/registrations/amf-non-3gpp-access",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> putAmfNon3gppAccess(@ApiParam(value = "ueId. ",required=true) @PathVariable("ueId") String ueId,@ApiParam(value = "The AMF registration for non 3GPP access is replaced with the received information." ,required=true )   @RequestBody AmfNon3GppAccessRegistration amfNon3gppAccessRegistration);

}
