apiVersion: v1
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: namfcommapi
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: namfcommapi:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: http://192.168.122.100:10080/ncos-1sd1/CoreStudy.git
      sourceSecret:
        name: ota-basicsecret
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: base-java8:latest
        incremental: false
        scripts: image:///opt/s2i/destination/src/Namf_Comm_API/openshift/.s2i/bin
      type: Source
    triggers:
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    name: namfcommapi
  spec:
    replicas: 1
    selector:
      name: namfcommapi
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: namfcommapi
      spec:
        containers:
        - env:
          - name: N1N2PATH
            value: http://uerandummyapi:8080/
          - name: AMFPATH
            value: http://namfcommapi:8080/
          - name: SMFPATH
            value: http://nsmfpdusessionapi:8080/
          - name: UECMPATH
            value: http://nudmuecmapi:8080/
          - name: SDMPATH
            value: http://nudmsdmapi:8080/
          - name: PCFPATH
            value: http://npcftmpadd:8080/
          - name: UDMPATH
            value: http://nudmtmpadd:8080/
          - name: NEC_5GS_CONT_GS_TIMER
            value: 5000
          image: namfcommapi:latest
          imagePullPolicy: Always
          name: namfcommapi-latest
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - namfcommapi-latest
        from:
          kind: ImageStreamTag
          name: namfcommapi:latest
          namespace: test-s2i
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    generation: 1
    name: namfcommapi
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: namfcommapi
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: namfcommapi
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
