// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PolicyCounter.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "PolicyCounter.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace SAC {
class PolicyCounterDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<PolicyCounter> {
} _PolicyCounter_default_instance_;

namespace protobuf_PolicyCounter_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PolicyCounter, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PolicyCounter, pid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PolicyCounter, pcs_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(PolicyCounter)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_PolicyCounter_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "PolicyCounter.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _PolicyCounter_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _PolicyCounter_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\023PolicyCounter.proto\022\003SAC\")\n\rPolicyCoun"
      "ter\022\013\n\003PID\030\001 \001(\005\022\013\n\003PCS\030\002 \001(\005b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 77);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "PolicyCounter.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_PolicyCounter_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PolicyCounter::kPIDFieldNumber;
const int PolicyCounter::kPCSFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PolicyCounter::PolicyCounter()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_PolicyCounter_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:SAC.PolicyCounter)
}
PolicyCounter::PolicyCounter(const PolicyCounter& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&pid_, &from.pid_,
    reinterpret_cast<char*>(&pcs_) -
    reinterpret_cast<char*>(&pid_) + sizeof(pcs_));
  // @@protoc_insertion_point(copy_constructor:SAC.PolicyCounter)
}

void PolicyCounter::SharedCtor() {
  ::memset(&pid_, 0, reinterpret_cast<char*>(&pcs_) -
    reinterpret_cast<char*>(&pid_) + sizeof(pcs_));
  _cached_size_ = 0;
}

PolicyCounter::~PolicyCounter() {
  // @@protoc_insertion_point(destructor:SAC.PolicyCounter)
  SharedDtor();
}

void PolicyCounter::SharedDtor() {
}

void PolicyCounter::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PolicyCounter::descriptor() {
  protobuf_PolicyCounter_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_PolicyCounter_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PolicyCounter& PolicyCounter::default_instance() {
  protobuf_PolicyCounter_2eproto::InitDefaults();
  return *internal_default_instance();
}

PolicyCounter* PolicyCounter::New(::google::protobuf::Arena* arena) const {
  PolicyCounter* n = new PolicyCounter;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PolicyCounter::Clear() {
// @@protoc_insertion_point(message_clear_start:SAC.PolicyCounter)
  ::memset(&pid_, 0, reinterpret_cast<char*>(&pcs_) -
    reinterpret_cast<char*>(&pid_) + sizeof(pcs_));
}

bool PolicyCounter::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:SAC.PolicyCounter)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 PID = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &pid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 PCS = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &pcs_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:SAC.PolicyCounter)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:SAC.PolicyCounter)
  return false;
#undef DO_
}

void PolicyCounter::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:SAC.PolicyCounter)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 PID = 1;
  if (this->pid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->pid(), output);
  }

  // int32 PCS = 2;
  if (this->pcs() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->pcs(), output);
  }

  // @@protoc_insertion_point(serialize_end:SAC.PolicyCounter)
}

::google::protobuf::uint8* PolicyCounter::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:SAC.PolicyCounter)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 PID = 1;
  if (this->pid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->pid(), target);
  }

  // int32 PCS = 2;
  if (this->pcs() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->pcs(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:SAC.PolicyCounter)
  return target;
}

size_t PolicyCounter::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SAC.PolicyCounter)
  size_t total_size = 0;

  // int32 PID = 1;
  if (this->pid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->pid());
  }

  // int32 PCS = 2;
  if (this->pcs() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->pcs());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PolicyCounter::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:SAC.PolicyCounter)
  GOOGLE_DCHECK_NE(&from, this);
  const PolicyCounter* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PolicyCounter>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:SAC.PolicyCounter)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:SAC.PolicyCounter)
    MergeFrom(*source);
  }
}

void PolicyCounter::MergeFrom(const PolicyCounter& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SAC.PolicyCounter)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.pid() != 0) {
    set_pid(from.pid());
  }
  if (from.pcs() != 0) {
    set_pcs(from.pcs());
  }
}

void PolicyCounter::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:SAC.PolicyCounter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PolicyCounter::CopyFrom(const PolicyCounter& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SAC.PolicyCounter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PolicyCounter::IsInitialized() const {
  return true;
}

void PolicyCounter::Swap(PolicyCounter* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PolicyCounter::InternalSwap(PolicyCounter* other) {
  std::swap(pid_, other->pid_);
  std::swap(pcs_, other->pcs_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PolicyCounter::GetMetadata() const {
  protobuf_PolicyCounter_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_PolicyCounter_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PolicyCounter

// int32 PID = 1;
void PolicyCounter::clear_pid() {
  pid_ = 0;
}
::google::protobuf::int32 PolicyCounter::pid() const {
  // @@protoc_insertion_point(field_get:SAC.PolicyCounter.PID)
  return pid_;
}
void PolicyCounter::set_pid(::google::protobuf::int32 value) {
  
  pid_ = value;
  // @@protoc_insertion_point(field_set:SAC.PolicyCounter.PID)
}

// int32 PCS = 2;
void PolicyCounter::clear_pcs() {
  pcs_ = 0;
}
::google::protobuf::int32 PolicyCounter::pcs() const {
  // @@protoc_insertion_point(field_get:SAC.PolicyCounter.PCS)
  return pcs_;
}
void PolicyCounter::set_pcs(::google::protobuf::int32 value) {
  
  pcs_ = value;
  // @@protoc_insertion_point(field_set:SAC.PolicyCounter.PCS)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace SAC

// @@protoc_insertion_point(global_scope)
