/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.nec.corestudy.amf.NamfCommunication.api;

import com.nec.corestudy.amf.NamfCommunication.model.AMFCreatedSubscriptionData;
import com.nec.corestudy.amf.NamfCommunication.model.AMFSubscriptionData;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-05-22T15:31:52.210+09:00")

@Api(value = "subscriptions", description = "the subscriptions API")
public interface SubscriptionsApi {

    @ApiOperation(value = "AMF Status Change Subscribe", nickname = "postAMFStatusChangeSubscribe", notes = "see 29.518 6.1.3.3", response = AMFCreatedSubscriptionData.class, tags={ "AMF Status Change Subscribe", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "CREATED.", response = AMFCreatedSubscriptionData.class) })
    @RequestMapping(value = "/subscriptions",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<AMFCreatedSubscriptionData> postAMFStatusChangeSubscribe(@ApiParam(value = "The request body contains the input parameters for the subscription." ,required=true )  @Valid @RequestBody AMFSubscriptionData subscriptionData);

}
