/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.nec.corestudy.smf.Controller.Nsmf_PDUSession.api;

import com.nec.corestudy.smf.Controller.Nsmf_PDUSession.model.HsmfUpdateData;
import com.nec.corestudy.smf.Controller.Nsmf_PDUSession.model.HsmfUpdatedData;
import com.nec.corestudy.smf.Controller.Nsmf_PDUSession.model.PduSessionCreateData;
import com.nec.corestudy.smf.Controller.Nsmf_PDUSession.model.PduSessionCreatedData;
import com.nec.corestudy.smf.Controller.Nsmf_PDUSession.model.ReleaseData;
import com.nec.corestudy.smf.Controller.Nsmf_PDUSession.model.ReleasedData;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-06-11T17:31:20.195+09:00")

@Api(value = "pdu-sessions", description = "the pdu-sessions API")
public interface PduSessionsApi {

    @ApiOperation(value = "Create PDU session service operation", nickname = "createPDUSession", notes = "This resource represents the collection of the individual PDU session created in the SMF.", response = PduSessionCreatedData.class, tags={ "PDU sessions collection", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "successful operation", response = PduSessionCreatedData.class) })
    @RequestMapping(value = "/pdu-sessions",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<PduSessionCreatedData> createPDUSession(@ApiParam(value = "Representation of the SM context to be created in the SMF"  )  @Valid @RequestBody PduSessionCreateData body);


    @ApiOperation(value = "Release PDU session", nickname = "releasePDUSession", notes = "This custom operation releases an individual SM context resource in the SMF, or in V-SMF in HR roaming scenario", response = ReleasedData.class, tags={ "Individual PDU session", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = ReleasedData.class),
        @ApiResponse(code = 204, message = "No Content") })
    @RequestMapping(value = "/pdu-sessions/{pduSessionRef}/release",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<ReleasedData> releasePDUSession(@ApiParam(value = "",required=true) @PathVariable("pduSessionRef") Long pduSessionRef,@ApiParam(value = "Representation of the data to be sent to the SMF when releasing the SM context."  )  @Valid @RequestBody ReleaseData body);


    @ApiOperation(value = "Update PDU session service operation", nickname = "updatePDUSession", notes = "MultipleThis method updates an individual SM context resource and/or provide N1 or N2 SM information received from the UE or the AN, for a given PDU session, towards the SMF, or in V-SMF in HR roaming scenario.", response = HsmfUpdatedData.class, tags={ "Individual PDU session", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = HsmfUpdatedData.class),
        @ApiResponse(code = 204, message = "No Content") })
    @RequestMapping(value = "/pdu-sessions/{pduSessionRef}",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.PATCH)
    ResponseEntity<HsmfUpdatedData> updatePDUSession(@ApiParam(value = "PDU session reference",required=true) @PathVariable("pduSessionRef") Long pduSessionRef,@ApiParam(value = "Representation of the updates to apply to the SM context." ,required=true )  @Valid @RequestBody HsmfUpdateData body);

}
