/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.nec.corestudy.amf.NamfSdmCLI.api;

import com.nec.corestudy.amf.NamfSdmCLI.model.IdTranslationResult;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-15T18:19:45.878+09:00")

@Api(value = "IdTranslationResult", description = "the IdTranslationResult API")
public interface IdTranslationResultApi {

    @ApiOperation(value = "IdTranslationResult", nickname = "getIdTranslationResult", notes = "see 29.503 6.1.3.12", response = IdTranslationResult.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "success", response = IdTranslationResult.class) })
    @RequestMapping(value = "/{gpsi}/id-translation-result",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.GET)
    ResponseEntity<IdTranslationResult> getIdTranslationResult(@ApiParam(value = "",required=true) @PathVariable("gpsi") String gpsi,@ApiParam(value = "[TBD].")  @RequestParam(value = "supportedFeatures", required = false) String supportedFeatures);

}
