/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.nec.corestudy.amf.NamfSdmCLI.api;

import com.nec.corestudy.amf.NamfSdmCLI.model.SmsManagementSubscriptionData;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-15T18:19:45.878+09:00")

@Api(value = "SmsManagementSubscriptionData", description = "the SmsManagementSubscriptionData API")
public interface SmsManagementSubscriptionDataApi {

    @ApiOperation(value = "SMSManagementSubscriptionData", nickname = "getSmsMngData", notes = "see 29.503 6.1.3.10", response = SmsManagementSubscriptionData.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "success", response = SmsManagementSubscriptionData.class) })
    @RequestMapping(value = "/{supi}/sms-mng-data",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.GET)
    ResponseEntity<SmsManagementSubscriptionData> getSmsMngData(@ApiParam(value = "",required=true) @PathVariable("supi") String supi);

}
