/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.nec.corestudy.amf.NamfSdmCLI.api;

import com.nec.corestudy.amf.NamfSdmCLI.model.SdmSubscription;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-15T18:19:45.878+09:00")

@Api(value = "SubscriptionData_", description = "the SubscriptionData_ API")
public interface SubscriptionData_Api {

    @ApiOperation(value = "Delete the subscription identified by {subscriptionId}, i.e. unsubscribe.", nickname = "deleteSDMSubscription", notes = "Delete the subscription identified by {subscriptionId}, i.e. unsubscribe.", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "Upon success, an empty response body shall be returned.") })
    @RequestMapping(value = "/{supi}/sdm-subscriptions/{subscriptionId}",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteSDMSubscription(@ApiParam(value = "Represents the Subscription Permanent Identifier. ",required=true) @PathVariable("supi") String supi,@ApiParam(value = "The subscriptionId identifies an individual subscription to notifications. The value is allocated by the UDM  during creation of the Subscription resource.",required=true) @PathVariable("subscriptionId") String subscriptionId);


    @ApiOperation(value = "Create a subscription.", nickname = "postSDMSubscription", notes = "see 29.503 6.1.3.3. ", response = SdmSubscription.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Upon success, a response body containing a representation of the created Individual subscription resource shall be returned. The HTTP response shall include a \"Location\" HTTP header that contains the resource URI of the created resource.", response = SdmSubscription.class) })
    @RequestMapping(value = "/{supi}/sdm-subscriptions",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<SdmSubscription> postSDMSubscription(@ApiParam(value = ".",required=true) @PathVariable("supi") String supi,@ApiParam(value = "The subscription that is to be created." ,required=true )   @RequestBody SdmSubscription subdata);

}
