/*
 * Nudm_SDM API
 * This is a UDM Server API.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 0.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Arp
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-21T18:27:13.711+09:00")
public class Arp {
  @SerializedName("priorityLevel")
  private Integer priorityLevel = null;

  /**
   * Gets or Sets preemptCap
   */
  @JsonAdapter(PreemptCapEnum.Adapter.class)
  public enum PreemptCapEnum {
    NOT_PREEMPT("NOT_PREEMPT"),
    
    MAY_PREEMPT("MAY_PREEMPT");

    private String value;

    PreemptCapEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PreemptCapEnum fromValue(String text) {
      for (PreemptCapEnum b : PreemptCapEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<PreemptCapEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PreemptCapEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PreemptCapEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return PreemptCapEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("preemptCap")
  private PreemptCapEnum preemptCap = null;

  /**
   * Gets or Sets preemptVuln
   */
  @JsonAdapter(PreemptVulnEnum.Adapter.class)
  public enum PreemptVulnEnum {
    NOT_PREEMPTABLE("NOT_PREEMPTABLE"),
    
    PREEMPTABLE("PREEMPTABLE");

    private String value;

    PreemptVulnEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PreemptVulnEnum fromValue(String text) {
      for (PreemptVulnEnum b : PreemptVulnEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<PreemptVulnEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PreemptVulnEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PreemptVulnEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return PreemptVulnEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("preemptVuln")
  private PreemptVulnEnum preemptVuln = null;

  public Arp priorityLevel(Integer priorityLevel) {
    this.priorityLevel = priorityLevel;
    return this;
  }

   /**
   * Get priorityLevel
   * @return priorityLevel
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getPriorityLevel() {
    return priorityLevel;
  }

  public void setPriorityLevel(Integer priorityLevel) {
    this.priorityLevel = priorityLevel;
  }

  public Arp preemptCap(PreemptCapEnum preemptCap) {
    this.preemptCap = preemptCap;
    return this;
  }

   /**
   * Get preemptCap
   * @return preemptCap
  **/
  @ApiModelProperty(required = true, value = "")
  public PreemptCapEnum getPreemptCap() {
    return preemptCap;
  }

  public void setPreemptCap(PreemptCapEnum preemptCap) {
    this.preemptCap = preemptCap;
  }

  public Arp preemptVuln(PreemptVulnEnum preemptVuln) {
    this.preemptVuln = preemptVuln;
    return this;
  }

   /**
   * Get preemptVuln
   * @return preemptVuln
  **/
  @ApiModelProperty(required = true, value = "")
  public PreemptVulnEnum getPreemptVuln() {
    return preemptVuln;
  }

  public void setPreemptVuln(PreemptVulnEnum preemptVuln) {
    this.preemptVuln = preemptVuln;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Arp arp = (Arp) o;
    return Objects.equals(this.priorityLevel, arp.priorityLevel) &&
        Objects.equals(this.preemptCap, arp.preemptCap) &&
        Objects.equals(this.preemptVuln, arp.preemptVuln);
  }

  @Override
  public int hashCode() {
    return Objects.hash(priorityLevel, preemptCap, preemptVuln);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Arp {\n");
    
    sb.append("    priorityLevel: ").append(toIndentedString(priorityLevel)).append("\n");
    sb.append("    preemptCap: ").append(toIndentedString(preemptCap)).append("\n");
    sb.append("    preemptVuln: ").append(toIndentedString(preemptVuln)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

