/*
 * Nudm_SDM API
 * This is a UDM Server API.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 0.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.model.Snssai;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Nssai
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-21T18:27:13.711+09:00")
public class Nssai {
  @SerializedName("supportedFeatures")
  private String supportedFeatures = null;

  @SerializedName("defaultSingleNssais")
  private List<Snssai> defaultSingleNssais = null;

  @SerializedName("singleNssais")
  private List<Snssai> singleNssais = null;

  public Nssai supportedFeatures(String supportedFeatures) {
    this.supportedFeatures = supportedFeatures;
    return this;
  }

   /**
   * Get supportedFeatures
   * @return supportedFeatures
  **/
  @ApiModelProperty(value = "")
  public String getSupportedFeatures() {
    return supportedFeatures;
  }

  public void setSupportedFeatures(String supportedFeatures) {
    this.supportedFeatures = supportedFeatures;
  }

  public Nssai defaultSingleNssais(List<Snssai> defaultSingleNssais) {
    this.defaultSingleNssais = defaultSingleNssais;
    return this;
  }

  public Nssai addDefaultSingleNssaisItem(Snssai defaultSingleNssaisItem) {
    if (this.defaultSingleNssais == null) {
      this.defaultSingleNssais = new ArrayList<Snssai>();
    }
    this.defaultSingleNssais.add(defaultSingleNssaisItem);
    return this;
  }

   /**
   * Get defaultSingleNssais
   * @return defaultSingleNssais
  **/
  @ApiModelProperty(value = "")
  public List<Snssai> getDefaultSingleNssais() {
    return defaultSingleNssais;
  }

  public void setDefaultSingleNssais(List<Snssai> defaultSingleNssais) {
    this.defaultSingleNssais = defaultSingleNssais;
  }

  public Nssai singleNssais(List<Snssai> singleNssais) {
    this.singleNssais = singleNssais;
    return this;
  }

  public Nssai addSingleNssaisItem(Snssai singleNssaisItem) {
    if (this.singleNssais == null) {
      this.singleNssais = new ArrayList<Snssai>();
    }
    this.singleNssais.add(singleNssaisItem);
    return this;
  }

   /**
   * Get singleNssais
   * @return singleNssais
  **/
  @ApiModelProperty(value = "")
  public List<Snssai> getSingleNssais() {
    return singleNssais;
  }

  public void setSingleNssais(List<Snssai> singleNssais) {
    this.singleNssais = singleNssais;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Nssai nssai = (Nssai) o;
    return Objects.equals(this.supportedFeatures, nssai.supportedFeatures) &&
        Objects.equals(this.defaultSingleNssais, nssai.defaultSingleNssais) &&
        Objects.equals(this.singleNssais, nssai.singleNssais);
  }

  @Override
  public int hashCode() {
    return Objects.hash(supportedFeatures, defaultSingleNssais, singleNssais);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Nssai {\n");
    
    sb.append("    supportedFeatures: ").append(toIndentedString(supportedFeatures)).append("\n");
    sb.append("    defaultSingleNssais: ").append(toIndentedString(defaultSingleNssais)).append("\n");
    sb.append("    singleNssais: ").append(toIndentedString(singleNssais)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

