/*
 * Nudm_SDM API
 * This is a UDM Server API.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 0.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * PduSessionTypes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-21T18:27:13.711+09:00")
public class PduSessionTypes {
  /**
   * Gets or Sets defaultSessionType
   */
  @JsonAdapter(DefaultSessionTypeEnum.Adapter.class)
  public enum DefaultSessionTypeEnum {
    IPV4V6("IPV4V6"),
    
    IPV4("IPV4"),
    
    IPV6("IPV6"),
    
    UNSTR("UNSTR"),
    
    ETHER("ETHER");

    private String value;

    DefaultSessionTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DefaultSessionTypeEnum fromValue(String text) {
      for (DefaultSessionTypeEnum b : DefaultSessionTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<DefaultSessionTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DefaultSessionTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DefaultSessionTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return DefaultSessionTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("defaultSessionType")
  private DefaultSessionTypeEnum defaultSessionType = null;

  /**
   * Gets or Sets allowedSessionType
   */
  @JsonAdapter(AllowedSessionTypeEnum.Adapter.class)
  public enum AllowedSessionTypeEnum {
    IPV4V6("IPV4V6"),
    
    IPV4("IPV4"),
    
    IPV6("IPV6"),
    
    UNSTR("UNSTR"),
    
    ETHER("ETHER");

    private String value;

    AllowedSessionTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AllowedSessionTypeEnum fromValue(String text) {
      for (AllowedSessionTypeEnum b : AllowedSessionTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<AllowedSessionTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AllowedSessionTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AllowedSessionTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return AllowedSessionTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("allowedSessionType")
  private List<AllowedSessionTypeEnum> allowedSessionType = null;

  public PduSessionTypes defaultSessionType(DefaultSessionTypeEnum defaultSessionType) {
    this.defaultSessionType = defaultSessionType;
    return this;
  }

   /**
   * Get defaultSessionType
   * @return defaultSessionType
  **/
  @ApiModelProperty(required = true, value = "")
  public DefaultSessionTypeEnum getDefaultSessionType() {
    return defaultSessionType;
  }

  public void setDefaultSessionType(DefaultSessionTypeEnum defaultSessionType) {
    this.defaultSessionType = defaultSessionType;
  }

  public PduSessionTypes allowedSessionType(List<AllowedSessionTypeEnum> allowedSessionType) {
    this.allowedSessionType = allowedSessionType;
    return this;
  }

  public PduSessionTypes addAllowedSessionTypeItem(AllowedSessionTypeEnum allowedSessionTypeItem) {
    if (this.allowedSessionType == null) {
      this.allowedSessionType = new ArrayList<AllowedSessionTypeEnum>();
    }
    this.allowedSessionType.add(allowedSessionTypeItem);
    return this;
  }

   /**
   * Get allowedSessionType
   * @return allowedSessionType
  **/
  @ApiModelProperty(value = "")
  public List<AllowedSessionTypeEnum> getAllowedSessionType() {
    return allowedSessionType;
  }

  public void setAllowedSessionType(List<AllowedSessionTypeEnum> allowedSessionType) {
    this.allowedSessionType = allowedSessionType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PduSessionTypes pduSessionTypes = (PduSessionTypes) o;
    return Objects.equals(this.defaultSessionType, pduSessionTypes.defaultSessionType) &&
        Objects.equals(this.allowedSessionType, pduSessionTypes.allowedSessionType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(defaultSessionType, allowedSessionType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PduSessionTypes {\n");
    
    sb.append("    defaultSessionType: ").append(toIndentedString(defaultSessionType)).append("\n");
    sb.append("    allowedSessionType: ").append(toIndentedString(allowedSessionType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

