/*
 * Nudm_SDM API
 * This is a UDM Server API.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 0.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PduSession
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-21T18:27:13.711+09:00")
public class PduSession {
  @SerializedName("pduSessionId")
  private Integer pduSessionId = null;

  @SerializedName("dnn")
  private String dnn = null;

  @SerializedName("smfId")
  private String smfId = null;

  @SerializedName("smfAddress")
  private String smfAddress = null;

  public PduSession pduSessionId(Integer pduSessionId) {
    this.pduSessionId = pduSessionId;
    return this;
  }

   /**
   * Get pduSessionId
   * @return pduSessionId
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getPduSessionId() {
    return pduSessionId;
  }

  public void setPduSessionId(Integer pduSessionId) {
    this.pduSessionId = pduSessionId;
  }

  public PduSession dnn(String dnn) {
    this.dnn = dnn;
    return this;
  }

   /**
   * Get dnn
   * @return dnn
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDnn() {
    return dnn;
  }

  public void setDnn(String dnn) {
    this.dnn = dnn;
  }

  public PduSession smfId(String smfId) {
    this.smfId = smfId;
    return this;
  }

   /**
   * Get smfId
   * @return smfId
  **/
  @ApiModelProperty(required = true, value = "")
  public String getSmfId() {
    return smfId;
  }

  public void setSmfId(String smfId) {
    this.smfId = smfId;
  }

  public PduSession smfAddress(String smfAddress) {
    this.smfAddress = smfAddress;
    return this;
  }

   /**
   * Get smfAddress
   * @return smfAddress
  **/
  @ApiModelProperty(required = true, value = "")
  public String getSmfAddress() {
    return smfAddress;
  }

  public void setSmfAddress(String smfAddress) {
    this.smfAddress = smfAddress;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PduSession pduSession = (PduSession) o;
    return Objects.equals(this.pduSessionId, pduSession.pduSessionId) &&
        Objects.equals(this.dnn, pduSession.dnn) &&
        Objects.equals(this.smfId, pduSession.smfId) &&
        Objects.equals(this.smfAddress, pduSession.smfAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pduSessionId, dnn, smfId, smfAddress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PduSession {\n");
    
    sb.append("    pduSessionId: ").append(toIndentedString(pduSessionId)).append("\n");
    sb.append("    dnn: ").append(toIndentedString(dnn)).append("\n");
    sb.append("    smfId: ").append(toIndentedString(smfId)).append("\n");
    sb.append("    smfAddress: ").append(toIndentedString(smfAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

