/*
 * Nudm_SDM API
 * This is a UDM Server API.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 0.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets PreemptionCapability
 */
@JsonAdapter(PreemptionCapability.Adapter.class)
public enum PreemptionCapability {
  
  NOT_PREEMPT("NOT_PREEMPT"),
  
  MAY_PREEMPT("MAY_PREEMPT");

  private String value;

  PreemptionCapability(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PreemptionCapability fromValue(String text) {
    for (PreemptionCapability b : PreemptionCapability.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<PreemptionCapability> {
    @Override
    public void write(final JsonWriter jsonWriter, final PreemptionCapability enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PreemptionCapability read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PreemptionCapability.fromValue(String.valueOf(value));
    }
  }
}

