/*
 * Nudm_SDM API
 * This is a UDM Server API.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 0.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SdmSubscription
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-21T18:27:13.711+09:00")
public class SdmSubscription {
  @SerializedName("callbackReference")
  private String callbackReference = null;

  @SerializedName("monitoredResourceUri")
  private List<String> monitoredResourceUri = new ArrayList<String>();

  public SdmSubscription callbackReference(String callbackReference) {
    this.callbackReference = callbackReference;
    return this;
  }

   /**
   * Get callbackReference
   * @return callbackReference
  **/
  @ApiModelProperty(required = true, value = "")
  public String getCallbackReference() {
    return callbackReference;
  }

  public void setCallbackReference(String callbackReference) {
    this.callbackReference = callbackReference;
  }

  public SdmSubscription monitoredResourceUri(List<String> monitoredResourceUri) {
    this.monitoredResourceUri = monitoredResourceUri;
    return this;
  }

  public SdmSubscription addMonitoredResourceUriItem(String monitoredResourceUriItem) {
    this.monitoredResourceUri.add(monitoredResourceUriItem);
    return this;
  }

   /**
   * Get monitoredResourceUri
   * @return monitoredResourceUri
  **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getMonitoredResourceUri() {
    return monitoredResourceUri;
  }

  public void setMonitoredResourceUri(List<String> monitoredResourceUri) {
    this.monitoredResourceUri = monitoredResourceUri;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SdmSubscription sdmSubscription = (SdmSubscription) o;
    return Objects.equals(this.callbackReference, sdmSubscription.callbackReference) &&
        Objects.equals(this.monitoredResourceUri, sdmSubscription.monitoredResourceUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callbackReference, monitoredResourceUri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SdmSubscription {\n");
    
    sb.append("    callbackReference: ").append(toIndentedString(callbackReference)).append("\n");
    sb.append("    monitoredResourceUri: ").append(toIndentedString(monitoredResourceUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

