/*
 * Nudm_SDM API
 * This is a UDM Server API.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 0.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.model.DnnConfiguration;
import com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.model.Snssai;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SessionManagementSubscriptionData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-21T18:27:13.711+09:00")
public class SessionManagementSubscriptionData {
  @SerializedName("singleNssai")
  private Snssai singleNssai = null;

  @SerializedName("dnnConfiguration")
  private List<DnnConfiguration> dnnConfiguration = null;

  public SessionManagementSubscriptionData singleNssai(Snssai singleNssai) {
    this.singleNssai = singleNssai;
    return this;
  }

   /**
   * Get singleNssai
   * @return singleNssai
  **/
  @ApiModelProperty(required = true, value = "")
  public Snssai getSingleNssai() {
    return singleNssai;
  }

  public void setSingleNssai(Snssai singleNssai) {
    this.singleNssai = singleNssai;
  }

  public SessionManagementSubscriptionData dnnConfiguration(List<DnnConfiguration> dnnConfiguration) {
    this.dnnConfiguration = dnnConfiguration;
    return this;
  }

  public SessionManagementSubscriptionData addDnnConfigurationItem(DnnConfiguration dnnConfigurationItem) {
    if (this.dnnConfiguration == null) {
      this.dnnConfiguration = new ArrayList<DnnConfiguration>();
    }
    this.dnnConfiguration.add(dnnConfigurationItem);
    return this;
  }

   /**
   * Get dnnConfiguration
   * @return dnnConfiguration
  **/
  @ApiModelProperty(value = "")
  public List<DnnConfiguration> getDnnConfiguration() {
    return dnnConfiguration;
  }

  public void setDnnConfiguration(List<DnnConfiguration> dnnConfiguration) {
    this.dnnConfiguration = dnnConfiguration;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionManagementSubscriptionData sessionManagementSubscriptionData = (SessionManagementSubscriptionData) o;
    return Objects.equals(this.singleNssai, sessionManagementSubscriptionData.singleNssai) &&
        Objects.equals(this.dnnConfiguration, sessionManagementSubscriptionData.dnnConfiguration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(singleNssai, dnnConfiguration);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionManagementSubscriptionData {\n");
    
    sb.append("    singleNssai: ").append(toIndentedString(singleNssai)).append("\n");
    sb.append("    dnnConfiguration: ").append(toIndentedString(dnnConfiguration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

