/*
 * Nudm_SDM API
 * This is a UDM Server API.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 0.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.model.PduSession;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * UeContextInSmfData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-21T18:27:13.711+09:00")
public class UeContextInSmfData {
  @SerializedName("pduSessions")
  private List<PduSession> pduSessions = null;

  public UeContextInSmfData pduSessions(List<PduSession> pduSessions) {
    this.pduSessions = pduSessions;
    return this;
  }

  public UeContextInSmfData addPduSessionsItem(PduSession pduSessionsItem) {
    if (this.pduSessions == null) {
      this.pduSessions = new ArrayList<PduSession>();
    }
    this.pduSessions.add(pduSessionsItem);
    return this;
  }

   /**
   * Get pduSessions
   * @return pduSessions
  **/
  @ApiModelProperty(value = "")
  public List<PduSession> getPduSessions() {
    return pduSessions;
  }

  public void setPduSessions(List<PduSession> pduSessions) {
    this.pduSessions = pduSessions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UeContextInSmfData ueContextInSmfData = (UeContextInSmfData) o;
    return Objects.equals(this.pduSessions, ueContextInSmfData.pduSessions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pduSessions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UeContextInSmfData {\n");
    
    sb.append("    pduSessions: ").append(toIndentedString(pduSessions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

