/*
 * Nudm_SDM API
 * This is a UDM Server API.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 0.6.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.api;

import com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.ApiCallback;
import com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.ApiClient;
import com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.ApiException;
import com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.ApiResponse;
import com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.Configuration;
import com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.Pair;
import com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.ProgressRequestBody;
import com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.nec.corestudy.smf.Controller.Nudm_SDM_API_client.model.SubscriptionDataSets;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SupiApi {
    private ApiClient apiClient;

    public SupiApi() {
        this(Configuration.getDefaultApiClient());
    }

    public SupiApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for getSupi
     * @param supi Represents the Subscription Permanent Identifier.  (required)
     * @param datasets [TBD]. (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getSupiCall(String supi, List<String> datasets, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/{supi}"
            .replaceAll("\\{" + "supi" + "\\}", apiClient.escapeString(supi.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (datasets != null)
        localVarCollectionQueryParams.addAll(apiClient.parameterToPairs("csv", "datasets", datasets));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/xml", "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json", "application/xml"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getSupiValidateBeforeCall(String supi, List<String> datasets, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'supi' is set
        if (supi == null) {
            throw new ApiException("Missing the required parameter 'supi' when calling getSupi(Async)");
        }
        
        // verify the required parameter 'datasets' is set
        if (datasets == null) {
            throw new ApiException("Missing the required parameter 'datasets' when calling getSupi(Async)");
        }
        

        com.squareup.okhttp.Call call = getSupiCall(supi, datasets, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Represents the Subscription Permanent Identifier.
     * see 29.503 6.1.3.11
     * @param supi Represents the Subscription Permanent Identifier.  (required)
     * @param datasets [TBD]. (required)
     * @return SubscriptionDataSets
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public SubscriptionDataSets getSupi(String supi, List<String> datasets) throws ApiException {
        ApiResponse<SubscriptionDataSets> resp = getSupiWithHttpInfo(supi, datasets);
        return resp.getData();
    }

    /**
     * Represents the Subscription Permanent Identifier.
     * see 29.503 6.1.3.11
     * @param supi Represents the Subscription Permanent Identifier.  (required)
     * @param datasets [TBD]. (required)
     * @return ApiResponse&lt;SubscriptionDataSets&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<SubscriptionDataSets> getSupiWithHttpInfo(String supi, List<String> datasets) throws ApiException {
        com.squareup.okhttp.Call call = getSupiValidateBeforeCall(supi, datasets, null, null);
        Type localVarReturnType = new TypeToken<SubscriptionDataSets>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Represents the Subscription Permanent Identifier. (asynchronously)
     * see 29.503 6.1.3.11
     * @param supi Represents the Subscription Permanent Identifier.  (required)
     * @param datasets [TBD]. (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getSupiAsync(String supi, List<String> datasets, final ApiCallback<SubscriptionDataSets> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getSupiValidateBeforeCall(supi, datasets, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<SubscriptionDataSets>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
