/*
 * gtpu_upf1
 * 21_add_gtpu_upf1.sh
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nec.corestudy.smf.Controller.VPPUPF_API_client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
