/*
 * Namf_Communication API
 * This is a AMF Server API.   [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nec.corestudy.smf.Controller.Namf_Communication_API_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nec.corestudy.smf.Controller.Namf_Communication_API_client.model.AMFArp;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AMFAssignEbiFailed
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-22T15:58:37.428+09:00")
public class AMFAssignEbiFailed {
  @SerializedName("pduSessionId")
  private Integer pduSessionId = null;

  @SerializedName("ailedArpList")
  private List<AMFArp> ailedArpList = null;

  public AMFAssignEbiFailed pduSessionId(Integer pduSessionId) {
    this.pduSessionId = pduSessionId;
    return this;
  }

   /**
   * Get pduSessionId
   * @return pduSessionId
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getPduSessionId() {
    return pduSessionId;
  }

  public void setPduSessionId(Integer pduSessionId) {
    this.pduSessionId = pduSessionId;
  }

  public AMFAssignEbiFailed ailedArpList(List<AMFArp> ailedArpList) {
    this.ailedArpList = ailedArpList;
    return this;
  }

  public AMFAssignEbiFailed addAiledArpListItem(AMFArp ailedArpListItem) {
    if (this.ailedArpList == null) {
      this.ailedArpList = new ArrayList<AMFArp>();
    }
    this.ailedArpList.add(ailedArpListItem);
    return this;
  }

   /**
   * Get ailedArpList
   * @return ailedArpList
  **/
  @ApiModelProperty(value = "")
  public List<AMFArp> getAiledArpList() {
    return ailedArpList;
  }

  public void setAiledArpList(List<AMFArp> ailedArpList) {
    this.ailedArpList = ailedArpList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AMFAssignEbiFailed amFAssignEbiFailed = (AMFAssignEbiFailed) o;
    return Objects.equals(this.pduSessionId, amFAssignEbiFailed.pduSessionId) &&
        Objects.equals(this.ailedArpList, amFAssignEbiFailed.ailedArpList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pduSessionId, ailedArpList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AMFAssignEbiFailed {\n");
    
    sb.append("    pduSessionId: ").append(toIndentedString(pduSessionId)).append("\n");
    sb.append("    ailedArpList: ").append(toIndentedString(ailedArpList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

