/*
 * Namf_Communication API
 * This is a AMF Server API.   [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nec.corestudy.smf.Controller.Namf_Communication_API_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nec.corestudy.smf.Controller.Namf_Communication_API_client.model.AMFArp;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AMFAssignEbiData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-22T15:58:37.428+09:00")
public class AMFAssignEbiData {
  @SerializedName("pduSessionId")
  private Integer pduSessionId = null;

  @SerializedName("arps")
  private List<AMFArp> arps = null;

  @SerializedName("releasedEbiList")
  private List<Integer> releasedEbiList = null;

  public AMFAssignEbiData pduSessionId(Integer pduSessionId) {
    this.pduSessionId = pduSessionId;
    return this;
  }

   /**
   * Get pduSessionId
   * @return pduSessionId
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getPduSessionId() {
    return pduSessionId;
  }

  public void setPduSessionId(Integer pduSessionId) {
    this.pduSessionId = pduSessionId;
  }

  public AMFAssignEbiData arps(List<AMFArp> arps) {
    this.arps = arps;
    return this;
  }

  public AMFAssignEbiData addArpsItem(AMFArp arpsItem) {
    if (this.arps == null) {
      this.arps = new ArrayList<AMFArp>();
    }
    this.arps.add(arpsItem);
    return this;
  }

   /**
   * Get arps
   * @return arps
  **/
  @ApiModelProperty(value = "")
  public List<AMFArp> getArps() {
    return arps;
  }

  public void setArps(List<AMFArp> arps) {
    this.arps = arps;
  }

  public AMFAssignEbiData releasedEbiList(List<Integer> releasedEbiList) {
    this.releasedEbiList = releasedEbiList;
    return this;
  }

  public AMFAssignEbiData addReleasedEbiListItem(Integer releasedEbiListItem) {
    if (this.releasedEbiList == null) {
      this.releasedEbiList = new ArrayList<Integer>();
    }
    this.releasedEbiList.add(releasedEbiListItem);
    return this;
  }

   /**
   * Get releasedEbiList
   * @return releasedEbiList
  **/
  @ApiModelProperty(value = "")
  public List<Integer> getReleasedEbiList() {
    return releasedEbiList;
  }

  public void setReleasedEbiList(List<Integer> releasedEbiList) {
    this.releasedEbiList = releasedEbiList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AMFAssignEbiData amFAssignEbiData = (AMFAssignEbiData) o;
    return Objects.equals(this.pduSessionId, amFAssignEbiData.pduSessionId) &&
        Objects.equals(this.arps, amFAssignEbiData.arps) &&
        Objects.equals(this.releasedEbiList, amFAssignEbiData.releasedEbiList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pduSessionId, arps, releasedEbiList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AMFAssignEbiData {\n");
    
    sb.append("    pduSessionId: ").append(toIndentedString(pduSessionId)).append("\n");
    sb.append("    arps: ").append(toIndentedString(arps)).append("\n");
    sb.append("    releasedEbiList: ").append(toIndentedString(releasedEbiList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

