/*
 * Namf_Communication API
 * This is a AMF Server API.   [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nec.corestudy.smf.Controller.Namf_Communication_API_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nec.corestudy.smf.Controller.Namf_Communication_API_client.model.AMFAreaOfValidity;
import com.nec.corestudy.smf.Controller.Namf_Communication_API_client.model.AMFN2SmInformation;
import com.nec.corestudy.smf.Controller.Namf_Communication_API_client.model.AMFNrppaInformation;
import com.nec.corestudy.smf.Controller.Namf_Communication_API_client.model.AMFPwsInformation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AMFN2InfoContainer
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-22T15:58:37.428+09:00")
public class AMFN2InfoContainer {
  /**
   * Gets or Sets n2InformationClass
   */
  @JsonAdapter(N2InformationClassEnum.Adapter.class)
  public enum N2InformationClassEnum {
    SM("Jamf_SM"),
    
    NRPPA("Jamf_NRPPa");

    private String value;

    N2InformationClassEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static N2InformationClassEnum fromValue(String text) {
      for (N2InformationClassEnum b : N2InformationClassEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<N2InformationClassEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final N2InformationClassEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public N2InformationClassEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return N2InformationClassEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("n2InformationClass")
  private N2InformationClassEnum n2InformationClass = null;

  @SerializedName("smInfo")
  private List<AMFN2SmInformation> smInfo = null;

  @SerializedName("nrppaInfo")
  private AMFNrppaInformation nrppaInfo = null;

  @SerializedName("pwsInfo")
  private AMFPwsInformation pwsInfo = null;

  @SerializedName("areaOfValidity")
  private AMFAreaOfValidity areaOfValidity = null;

  public AMFN2InfoContainer n2InformationClass(N2InformationClassEnum n2InformationClass) {
    this.n2InformationClass = n2InformationClass;
    return this;
  }

   /**
   * Get n2InformationClass
   * @return n2InformationClass
  **/
  @ApiModelProperty(required = true, value = "")
  public N2InformationClassEnum getN2InformationClass() {
    return n2InformationClass;
  }

  public void setN2InformationClass(N2InformationClassEnum n2InformationClass) {
    this.n2InformationClass = n2InformationClass;
  }

  public AMFN2InfoContainer smInfo(List<AMFN2SmInformation> smInfo) {
    this.smInfo = smInfo;
    return this;
  }

  public AMFN2InfoContainer addSmInfoItem(AMFN2SmInformation smInfoItem) {
    if (this.smInfo == null) {
      this.smInfo = new ArrayList<AMFN2SmInformation>();
    }
    this.smInfo.add(smInfoItem);
    return this;
  }

   /**
   * Get smInfo
   * @return smInfo
  **/
  @ApiModelProperty(value = "")
  public List<AMFN2SmInformation> getSmInfo() {
    return smInfo;
  }

  public void setSmInfo(List<AMFN2SmInformation> smInfo) {
    this.smInfo = smInfo;
  }

  public AMFN2InfoContainer nrppaInfo(AMFNrppaInformation nrppaInfo) {
    this.nrppaInfo = nrppaInfo;
    return this;
  }

   /**
   * Get nrppaInfo
   * @return nrppaInfo
  **/
  @ApiModelProperty(value = "")
  public AMFNrppaInformation getNrppaInfo() {
    return nrppaInfo;
  }

  public void setNrppaInfo(AMFNrppaInformation nrppaInfo) {
    this.nrppaInfo = nrppaInfo;
  }

  public AMFN2InfoContainer pwsInfo(AMFPwsInformation pwsInfo) {
    this.pwsInfo = pwsInfo;
    return this;
  }

   /**
   * Get pwsInfo
   * @return pwsInfo
  **/
  @ApiModelProperty(value = "")
  public AMFPwsInformation getPwsInfo() {
    return pwsInfo;
  }

  public void setPwsInfo(AMFPwsInformation pwsInfo) {
    this.pwsInfo = pwsInfo;
  }

  public AMFN2InfoContainer areaOfValidity(AMFAreaOfValidity areaOfValidity) {
    this.areaOfValidity = areaOfValidity;
    return this;
  }

   /**
   * Get areaOfValidity
   * @return areaOfValidity
  **/
  @ApiModelProperty(value = "")
  public AMFAreaOfValidity getAreaOfValidity() {
    return areaOfValidity;
  }

  public void setAreaOfValidity(AMFAreaOfValidity areaOfValidity) {
    this.areaOfValidity = areaOfValidity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AMFN2InfoContainer amFN2InfoContainer = (AMFN2InfoContainer) o;
    return Objects.equals(this.n2InformationClass, amFN2InfoContainer.n2InformationClass) &&
        Objects.equals(this.smInfo, amFN2InfoContainer.smInfo) &&
        Objects.equals(this.nrppaInfo, amFN2InfoContainer.nrppaInfo) &&
        Objects.equals(this.pwsInfo, amFN2InfoContainer.pwsInfo) &&
        Objects.equals(this.areaOfValidity, amFN2InfoContainer.areaOfValidity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(n2InformationClass, smInfo, nrppaInfo, pwsInfo, areaOfValidity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AMFN2InfoContainer {\n");
    
    sb.append("    n2InformationClass: ").append(toIndentedString(n2InformationClass)).append("\n");
    sb.append("    smInfo: ").append(toIndentedString(smInfo)).append("\n");
    sb.append("    nrppaInfo: ").append(toIndentedString(nrppaInfo)).append("\n");
    sb.append("    pwsInfo: ").append(toIndentedString(pwsInfo)).append("\n");
    sb.append("    areaOfValidity: ").append(toIndentedString(areaOfValidity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

