/*
 * Namf_Communication API
 * This is a AMF Server API.   [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nec.corestudy.smf.Controller.Namf_Communication_API_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nec.corestudy.smf.Controller.Namf_Communication_API_client.model.AMFArp;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AMFSingleAssignedEbi
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-22T15:58:37.428+09:00")
public class AMFSingleAssignedEbi {
  @SerializedName("arp")
  private AMFArp arp = null;

  @SerializedName("ebi")
  private Integer ebi = null;

  public AMFSingleAssignedEbi arp(AMFArp arp) {
    this.arp = arp;
    return this;
  }

   /**
   * Get arp
   * @return arp
  **/
  @ApiModelProperty(required = true, value = "")
  public AMFArp getArp() {
    return arp;
  }

  public void setArp(AMFArp arp) {
    this.arp = arp;
  }

  public AMFSingleAssignedEbi ebi(Integer ebi) {
    this.ebi = ebi;
    return this;
  }

   /**
   * Get ebi
   * @return ebi
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getEbi() {
    return ebi;
  }

  public void setEbi(Integer ebi) {
    this.ebi = ebi;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AMFSingleAssignedEbi amFSingleAssignedEbi = (AMFSingleAssignedEbi) o;
    return Objects.equals(this.arp, amFSingleAssignedEbi.arp) &&
        Objects.equals(this.ebi, amFSingleAssignedEbi.ebi);
  }

  @Override
  public int hashCode() {
    return Objects.hash(arp, ebi);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AMFSingleAssignedEbi {\n");
    
    sb.append("    arp: ").append(toIndentedString(arp)).append("\n");
    sb.append("    ebi: ").append(toIndentedString(ebi)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

