/*
 * Namf_Communication API
 * This is a AMF Server API.   [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nec.corestudy.smf.Controller.Namf_Communication_API_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nec.corestudy.smf.Controller.Namf_Communication_API_client.model.AMFAmfEventSubscription;
import com.nec.corestudy.smf.Controller.Namf_Communication_API_client.model.AMFMmContext;
import com.nec.corestudy.smf.Controller.Namf_Communication_API_client.model.AMFPduSessionContext;
import com.nec.corestudy.smf.Controller.Namf_Communication_API_client.model.AMFSeafData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AMFUeContext
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-22T15:58:37.428+09:00")
public class AMFUeContext {
  @SerializedName("supi")
  private String supi = null;

  @SerializedName("supiUnauthInd")
  private Boolean supiUnauthInd = null;

  @SerializedName("gpsi")
  private List<String> gpsi = null;

  @SerializedName("pei")
  private String pei = null;

  @SerializedName("groups")
  private List<String> groups = null;

  @SerializedName("drxParameter")
  private String drxParameter = null;

  @SerializedName("subRfsp")
  private Integer subRfsp = null;

  @SerializedName("usedRfsp")
  private Integer usedRfsp = null;

  /**
   * Gets or Sets smsSupport
   */
  @JsonAdapter(SmsSupportEnum.Adapter.class)
  public enum SmsSupportEnum {
    _3GPP("Jamf_3GPP"),
    
    NON_3GPP("Jamf_NON_3GPP"),
    
    BOTH("Jamf_BOTH"),
    
    NONE("Jamf_NONE");

    private String value;

    SmsSupportEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SmsSupportEnum fromValue(String text) {
      for (SmsSupportEnum b : SmsSupportEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<SmsSupportEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SmsSupportEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SmsSupportEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return SmsSupportEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("smsSupport")
  private SmsSupportEnum smsSupport = null;

  @SerializedName("smsfId")
  private String smsfId = null;

  @SerializedName("seafData")
  private AMFSeafData seafData = null;

  @SerializedName("pcfId")
  private String pcfId = null;

  @SerializedName("hpcfId")
  private String hpcfId = null;

  @SerializedName("eventSubscriptions")
  private List<AMFAmfEventSubscription> eventSubscriptions = null;

  @SerializedName("mmContexts")
  private List<AMFMmContext> mmContexts = null;

  @SerializedName("sessionContexts")
  private List<AMFPduSessionContext> sessionContexts = null;

  public AMFUeContext supi(String supi) {
    this.supi = supi;
    return this;
  }

   /**
   * Get supi
   * @return supi
  **/
  @ApiModelProperty(value = "")
  public String getSupi() {
    return supi;
  }

  public void setSupi(String supi) {
    this.supi = supi;
  }

  public AMFUeContext supiUnauthInd(Boolean supiUnauthInd) {
    this.supiUnauthInd = supiUnauthInd;
    return this;
  }

   /**
   * Get supiUnauthInd
   * @return supiUnauthInd
  **/
  @ApiModelProperty(value = "")
  public Boolean isSupiUnauthInd() {
    return supiUnauthInd;
  }

  public void setSupiUnauthInd(Boolean supiUnauthInd) {
    this.supiUnauthInd = supiUnauthInd;
  }

  public AMFUeContext gpsi(List<String> gpsi) {
    this.gpsi = gpsi;
    return this;
  }

  public AMFUeContext addGpsiItem(String gpsiItem) {
    if (this.gpsi == null) {
      this.gpsi = new ArrayList<String>();
    }
    this.gpsi.add(gpsiItem);
    return this;
  }

   /**
   * Get gpsi
   * @return gpsi
  **/
  @ApiModelProperty(value = "")
  public List<String> getGpsi() {
    return gpsi;
  }

  public void setGpsi(List<String> gpsi) {
    this.gpsi = gpsi;
  }

  public AMFUeContext pei(String pei) {
    this.pei = pei;
    return this;
  }

   /**
   * Get pei
   * @return pei
  **/
  @ApiModelProperty(value = "")
  public String getPei() {
    return pei;
  }

  public void setPei(String pei) {
    this.pei = pei;
  }

  public AMFUeContext groups(List<String> groups) {
    this.groups = groups;
    return this;
  }

  public AMFUeContext addGroupsItem(String groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<String>();
    }
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * Get groups
   * @return groups
  **/
  @ApiModelProperty(value = "")
  public List<String> getGroups() {
    return groups;
  }

  public void setGroups(List<String> groups) {
    this.groups = groups;
  }

  public AMFUeContext drxParameter(String drxParameter) {
    this.drxParameter = drxParameter;
    return this;
  }

   /**
   * Get drxParameter
   * @return drxParameter
  **/
  @ApiModelProperty(value = "")
  public String getDrxParameter() {
    return drxParameter;
  }

  public void setDrxParameter(String drxParameter) {
    this.drxParameter = drxParameter;
  }

  public AMFUeContext subRfsp(Integer subRfsp) {
    this.subRfsp = subRfsp;
    return this;
  }

   /**
   * Get subRfsp
   * @return subRfsp
  **/
  @ApiModelProperty(value = "")
  public Integer getSubRfsp() {
    return subRfsp;
  }

  public void setSubRfsp(Integer subRfsp) {
    this.subRfsp = subRfsp;
  }

  public AMFUeContext usedRfsp(Integer usedRfsp) {
    this.usedRfsp = usedRfsp;
    return this;
  }

   /**
   * Get usedRfsp
   * @return usedRfsp
  **/
  @ApiModelProperty(value = "")
  public Integer getUsedRfsp() {
    return usedRfsp;
  }

  public void setUsedRfsp(Integer usedRfsp) {
    this.usedRfsp = usedRfsp;
  }

  public AMFUeContext smsSupport(SmsSupportEnum smsSupport) {
    this.smsSupport = smsSupport;
    return this;
  }

   /**
   * Get smsSupport
   * @return smsSupport
  **/
  @ApiModelProperty(required = true, value = "")
  public SmsSupportEnum getSmsSupport() {
    return smsSupport;
  }

  public void setSmsSupport(SmsSupportEnum smsSupport) {
    this.smsSupport = smsSupport;
  }

  public AMFUeContext smsfId(String smsfId) {
    this.smsfId = smsfId;
    return this;
  }

   /**
   * Get smsfId
   * @return smsfId
  **/
  @ApiModelProperty(value = "")
  public String getSmsfId() {
    return smsfId;
  }

  public void setSmsfId(String smsfId) {
    this.smsfId = smsfId;
  }

  public AMFUeContext seafData(AMFSeafData seafData) {
    this.seafData = seafData;
    return this;
  }

   /**
   * Get seafData
   * @return seafData
  **/
  @ApiModelProperty(value = "")
  public AMFSeafData getSeafData() {
    return seafData;
  }

  public void setSeafData(AMFSeafData seafData) {
    this.seafData = seafData;
  }

  public AMFUeContext pcfId(String pcfId) {
    this.pcfId = pcfId;
    return this;
  }

   /**
   * Get pcfId
   * @return pcfId
  **/
  @ApiModelProperty(value = "")
  public String getPcfId() {
    return pcfId;
  }

  public void setPcfId(String pcfId) {
    this.pcfId = pcfId;
  }

  public AMFUeContext hpcfId(String hpcfId) {
    this.hpcfId = hpcfId;
    return this;
  }

   /**
   * Get hpcfId
   * @return hpcfId
  **/
  @ApiModelProperty(value = "")
  public String getHpcfId() {
    return hpcfId;
  }

  public void setHpcfId(String hpcfId) {
    this.hpcfId = hpcfId;
  }

  public AMFUeContext eventSubscriptions(List<AMFAmfEventSubscription> eventSubscriptions) {
    this.eventSubscriptions = eventSubscriptions;
    return this;
  }

  public AMFUeContext addEventSubscriptionsItem(AMFAmfEventSubscription eventSubscriptionsItem) {
    if (this.eventSubscriptions == null) {
      this.eventSubscriptions = new ArrayList<AMFAmfEventSubscription>();
    }
    this.eventSubscriptions.add(eventSubscriptionsItem);
    return this;
  }

   /**
   * Get eventSubscriptions
   * @return eventSubscriptions
  **/
  @ApiModelProperty(value = "")
  public List<AMFAmfEventSubscription> getEventSubscriptions() {
    return eventSubscriptions;
  }

  public void setEventSubscriptions(List<AMFAmfEventSubscription> eventSubscriptions) {
    this.eventSubscriptions = eventSubscriptions;
  }

  public AMFUeContext mmContexts(List<AMFMmContext> mmContexts) {
    this.mmContexts = mmContexts;
    return this;
  }

  public AMFUeContext addMmContextsItem(AMFMmContext mmContextsItem) {
    if (this.mmContexts == null) {
      this.mmContexts = new ArrayList<AMFMmContext>();
    }
    this.mmContexts.add(mmContextsItem);
    return this;
  }

   /**
   * Get mmContexts
   * @return mmContexts
  **/
  @ApiModelProperty(value = "")
  public List<AMFMmContext> getMmContexts() {
    return mmContexts;
  }

  public void setMmContexts(List<AMFMmContext> mmContexts) {
    this.mmContexts = mmContexts;
  }

  public AMFUeContext sessionContexts(List<AMFPduSessionContext> sessionContexts) {
    this.sessionContexts = sessionContexts;
    return this;
  }

  public AMFUeContext addSessionContextsItem(AMFPduSessionContext sessionContextsItem) {
    if (this.sessionContexts == null) {
      this.sessionContexts = new ArrayList<AMFPduSessionContext>();
    }
    this.sessionContexts.add(sessionContextsItem);
    return this;
  }

   /**
   * Get sessionContexts
   * @return sessionContexts
  **/
  @ApiModelProperty(value = "")
  public List<AMFPduSessionContext> getSessionContexts() {
    return sessionContexts;
  }

  public void setSessionContexts(List<AMFPduSessionContext> sessionContexts) {
    this.sessionContexts = sessionContexts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AMFUeContext amFUeContext = (AMFUeContext) o;
    return Objects.equals(this.supi, amFUeContext.supi) &&
        Objects.equals(this.supiUnauthInd, amFUeContext.supiUnauthInd) &&
        Objects.equals(this.gpsi, amFUeContext.gpsi) &&
        Objects.equals(this.pei, amFUeContext.pei) &&
        Objects.equals(this.groups, amFUeContext.groups) &&
        Objects.equals(this.drxParameter, amFUeContext.drxParameter) &&
        Objects.equals(this.subRfsp, amFUeContext.subRfsp) &&
        Objects.equals(this.usedRfsp, amFUeContext.usedRfsp) &&
        Objects.equals(this.smsSupport, amFUeContext.smsSupport) &&
        Objects.equals(this.smsfId, amFUeContext.smsfId) &&
        Objects.equals(this.seafData, amFUeContext.seafData) &&
        Objects.equals(this.pcfId, amFUeContext.pcfId) &&
        Objects.equals(this.hpcfId, amFUeContext.hpcfId) &&
        Objects.equals(this.eventSubscriptions, amFUeContext.eventSubscriptions) &&
        Objects.equals(this.mmContexts, amFUeContext.mmContexts) &&
        Objects.equals(this.sessionContexts, amFUeContext.sessionContexts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(supi, supiUnauthInd, gpsi, pei, groups, drxParameter, subRfsp, usedRfsp, smsSupport, smsfId, seafData, pcfId, hpcfId, eventSubscriptions, mmContexts, sessionContexts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AMFUeContext {\n");
    
    sb.append("    supi: ").append(toIndentedString(supi)).append("\n");
    sb.append("    supiUnauthInd: ").append(toIndentedString(supiUnauthInd)).append("\n");
    sb.append("    gpsi: ").append(toIndentedString(gpsi)).append("\n");
    sb.append("    pei: ").append(toIndentedString(pei)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    drxParameter: ").append(toIndentedString(drxParameter)).append("\n");
    sb.append("    subRfsp: ").append(toIndentedString(subRfsp)).append("\n");
    sb.append("    usedRfsp: ").append(toIndentedString(usedRfsp)).append("\n");
    sb.append("    smsSupport: ").append(toIndentedString(smsSupport)).append("\n");
    sb.append("    smsfId: ").append(toIndentedString(smsfId)).append("\n");
    sb.append("    seafData: ").append(toIndentedString(seafData)).append("\n");
    sb.append("    pcfId: ").append(toIndentedString(pcfId)).append("\n");
    sb.append("    hpcfId: ").append(toIndentedString(hpcfId)).append("\n");
    sb.append("    eventSubscriptions: ").append(toIndentedString(eventSubscriptions)).append("\n");
    sb.append("    mmContexts: ").append(toIndentedString(mmContexts)).append("\n");
    sb.append("    sessionContexts: ").append(toIndentedString(sessionContexts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

