/*
 * Namf_Communication API
 * This is a AMF Server API.   [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nec.corestudy.smf.Controller.Namf_Communication_API_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nec.corestudy.smf.Controller.Namf_Communication_API_client.model.AMFN2InfoContainer;
import com.nec.corestudy.smf.Controller.Namf_Communication_API_client.model.AMFN2InfoContent;
import com.nec.corestudy.smf.Controller.Namf_Communication_API_client.model.AMFUeContext;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AMFUeContextCreatedData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-22T15:58:37.428+09:00")
public class AMFUeContextCreatedData {
  @SerializedName("ueContext")
  private AMFUeContext ueContext = null;

  @SerializedName("targetToSourceData")
  private AMFN2InfoContainer targetToSourceData = null;

  @SerializedName("pduSessions")
  private List<AMFN2InfoContent> pduSessions = new ArrayList<AMFN2InfoContent>();

  @SerializedName("ngapCause")
  private Integer ngapCause = null;

  @SerializedName("failedSessions")
  private List<Integer> failedSessions = null;

  @SerializedName("supportedFeatures")
  private String supportedFeatures = null;

  public AMFUeContextCreatedData ueContext(AMFUeContext ueContext) {
    this.ueContext = ueContext;
    return this;
  }

   /**
   * Get ueContext
   * @return ueContext
  **/
  @ApiModelProperty(required = true, value = "")
  public AMFUeContext getUeContext() {
    return ueContext;
  }

  public void setUeContext(AMFUeContext ueContext) {
    this.ueContext = ueContext;
  }

  public AMFUeContextCreatedData targetToSourceData(AMFN2InfoContainer targetToSourceData) {
    this.targetToSourceData = targetToSourceData;
    return this;
  }

   /**
   * Get targetToSourceData
   * @return targetToSourceData
  **/
  @ApiModelProperty(required = true, value = "")
  public AMFN2InfoContainer getTargetToSourceData() {
    return targetToSourceData;
  }

  public void setTargetToSourceData(AMFN2InfoContainer targetToSourceData) {
    this.targetToSourceData = targetToSourceData;
  }

  public AMFUeContextCreatedData pduSessions(List<AMFN2InfoContent> pduSessions) {
    this.pduSessions = pduSessions;
    return this;
  }

  public AMFUeContextCreatedData addPduSessionsItem(AMFN2InfoContent pduSessionsItem) {
    this.pduSessions.add(pduSessionsItem);
    return this;
  }

   /**
   * Definition of N2SmInfoContent not found.
   * @return pduSessions
  **/
  @ApiModelProperty(required = true, value = "Definition of N2SmInfoContent not found.")
  public List<AMFN2InfoContent> getPduSessions() {
    return pduSessions;
  }

  public void setPduSessions(List<AMFN2InfoContent> pduSessions) {
    this.pduSessions = pduSessions;
  }

  public AMFUeContextCreatedData ngapCause(Integer ngapCause) {
    this.ngapCause = ngapCause;
    return this;
  }

   /**
   * Get ngapCause
   * @return ngapCause
  **/
  @ApiModelProperty(value = "")
  public Integer getNgapCause() {
    return ngapCause;
  }

  public void setNgapCause(Integer ngapCause) {
    this.ngapCause = ngapCause;
  }

  public AMFUeContextCreatedData failedSessions(List<Integer> failedSessions) {
    this.failedSessions = failedSessions;
    return this;
  }

  public AMFUeContextCreatedData addFailedSessionsItem(Integer failedSessionsItem) {
    if (this.failedSessions == null) {
      this.failedSessions = new ArrayList<Integer>();
    }
    this.failedSessions.add(failedSessionsItem);
    return this;
  }

   /**
   * Get failedSessions
   * @return failedSessions
  **/
  @ApiModelProperty(value = "")
  public List<Integer> getFailedSessions() {
    return failedSessions;
  }

  public void setFailedSessions(List<Integer> failedSessions) {
    this.failedSessions = failedSessions;
  }

  public AMFUeContextCreatedData supportedFeatures(String supportedFeatures) {
    this.supportedFeatures = supportedFeatures;
    return this;
  }

   /**
   * Get supportedFeatures
   * @return supportedFeatures
  **/
  @ApiModelProperty(value = "")
  public String getSupportedFeatures() {
    return supportedFeatures;
  }

  public void setSupportedFeatures(String supportedFeatures) {
    this.supportedFeatures = supportedFeatures;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AMFUeContextCreatedData amFUeContextCreatedData = (AMFUeContextCreatedData) o;
    return Objects.equals(this.ueContext, amFUeContextCreatedData.ueContext) &&
        Objects.equals(this.targetToSourceData, amFUeContextCreatedData.targetToSourceData) &&
        Objects.equals(this.pduSessions, amFUeContextCreatedData.pduSessions) &&
        Objects.equals(this.ngapCause, amFUeContextCreatedData.ngapCause) &&
        Objects.equals(this.failedSessions, amFUeContextCreatedData.failedSessions) &&
        Objects.equals(this.supportedFeatures, amFUeContextCreatedData.supportedFeatures);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ueContext, targetToSourceData, pduSessions, ngapCause, failedSessions, supportedFeatures);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AMFUeContextCreatedData {\n");
    
    sb.append("    ueContext: ").append(toIndentedString(ueContext)).append("\n");
    sb.append("    targetToSourceData: ").append(toIndentedString(targetToSourceData)).append("\n");
    sb.append("    pduSessions: ").append(toIndentedString(pduSessions)).append("\n");
    sb.append("    ngapCause: ").append(toIndentedString(ngapCause)).append("\n");
    sb.append("    failedSessions: ").append(toIndentedString(failedSessions)).append("\n");
    sb.append("    supportedFeatures: ").append(toIndentedString(supportedFeatures)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

