/*
 * Namf_Communication API
 * This is a AMF Server API.   [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nec.corestudy.smf.Controller.Namf_Communication_API_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nec.corestudy.smf.Controller.Namf_Communication_API_client.model.AMFUeContext;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AMFUeContextTransferRspData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-22T15:58:37.428+09:00")
public class AMFUeContextTransferRspData {
  @SerializedName("ueContext")
  private AMFUeContext ueContext = null;

  @SerializedName("regCompleteNotifyUri")
  private String regCompleteNotifyUri = null;

  @SerializedName("supportedFeatures")
  private String supportedFeatures = null;

  public AMFUeContextTransferRspData ueContext(AMFUeContext ueContext) {
    this.ueContext = ueContext;
    return this;
  }

   /**
   * Get ueContext
   * @return ueContext
  **/
  @ApiModelProperty(required = true, value = "")
  public AMFUeContext getUeContext() {
    return ueContext;
  }

  public void setUeContext(AMFUeContext ueContext) {
    this.ueContext = ueContext;
  }

  public AMFUeContextTransferRspData regCompleteNotifyUri(String regCompleteNotifyUri) {
    this.regCompleteNotifyUri = regCompleteNotifyUri;
    return this;
  }

   /**
   * Get regCompleteNotifyUri
   * @return regCompleteNotifyUri
  **/
  @ApiModelProperty(required = true, value = "")
  public String getRegCompleteNotifyUri() {
    return regCompleteNotifyUri;
  }

  public void setRegCompleteNotifyUri(String regCompleteNotifyUri) {
    this.regCompleteNotifyUri = regCompleteNotifyUri;
  }

  public AMFUeContextTransferRspData supportedFeatures(String supportedFeatures) {
    this.supportedFeatures = supportedFeatures;
    return this;
  }

   /**
   * Get supportedFeatures
   * @return supportedFeatures
  **/
  @ApiModelProperty(value = "")
  public String getSupportedFeatures() {
    return supportedFeatures;
  }

  public void setSupportedFeatures(String supportedFeatures) {
    this.supportedFeatures = supportedFeatures;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AMFUeContextTransferRspData amFUeContextTransferRspData = (AMFUeContextTransferRspData) o;
    return Objects.equals(this.ueContext, amFUeContextTransferRspData.ueContext) &&
        Objects.equals(this.regCompleteNotifyUri, amFUeContextTransferRspData.regCompleteNotifyUri) &&
        Objects.equals(this.supportedFeatures, amFUeContextTransferRspData.supportedFeatures);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ueContext, regCompleteNotifyUri, supportedFeatures);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AMFUeContextTransferRspData {\n");
    
    sb.append("    ueContext: ").append(toIndentedString(ueContext)).append("\n");
    sb.append("    regCompleteNotifyUri: ").append(toIndentedString(regCompleteNotifyUri)).append("\n");
    sb.append("    supportedFeatures: ").append(toIndentedString(supportedFeatures)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

