/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.nec.corestudy.amf.N1N2IF_CLI.api;

import com.nec.corestudy.amf.N1N2IF_CLI.model.AMFN2ResRelReqData;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-12T20:15:03.595+09:00")

@Api(value = "N2ResourceReleaseRequest", description = "the N2ResourceReleaseRequest API")
public interface N2ResourceReleaseRequestApi {

    @ApiOperation(value = "N2 Resource Release Request", nickname = "postN2ResourceReleaseRequest", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK.") })
    @RequestMapping(value = "/{ueId}/n2resource-release/request",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<?> postN2ResourceReleaseRequest(@ApiParam(value = "ueId.",required=true) @PathVariable("ueId") String ueId,@ApiParam(value = ""  )   @RequestBody AMFN2ResRelReqData n2ResRelReqData);

}
