/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.nec.corestudy.gnb.GTPU_GNB1.api;

import com.nec.corestudy.gnb.GTPU_GNB1.model.CreategtpuGnb;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-06-12T14:03:16.070+09:00")

@Api(value = "{teid}", description = "the {teid} API")
public interface TeidApi {

    @ApiOperation(value = "Tunnel Create", nickname = "tunnelCreate", notes = "", tags={ "Tunnel Create", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "successful operation") })
    @RequestMapping(value = "/{teid}/",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> tunnelCreate(@ApiParam(value = "",required=true) @PathVariable("teid") Integer teid,@ApiParam(value = "" ,required=true )  @Valid @RequestBody CreategtpuGnb body);


    @ApiOperation(value = "Tunnel Delete", nickname = "tunnelDelete", notes = "", tags={ "Tunnel Delete", })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "successful operation") })
    @RequestMapping(value = "/{teid}/",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.DELETE)
    ResponseEntity<Void> tunnelDelete(@ApiParam(value = "",required=true) @PathVariable("teid") Integer teid);

}
