/*
 * gtpu_upf1
 * 21_add_gtpu_upf1.sh
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nec.corestudy.smf.Controller.VPPUPF_API_client.api;

import com.nec.corestudy.smf.Controller.VPPUPF_API_client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TunnelDeleteApi
 */
@Ignore
public class TunnelDeleteApiTest {

    private final TunnelDeleteApi api = new TunnelDeleteApi();

    
    /**
     * Tunnel Delete
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void tunnelDeleteTest() throws ApiException {
        Integer teid = null;
        api.tunnelDelete(teid);

        // TODO: test validations
    }
    
}
